// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 chuahchengxi

import Foundation

/// What the buddy flings when it plays its move. Styles map to tiny pixel
/// sprites drawn at runtime; the catalogue picks one per species from a
/// hand-tuned signature table first, then from the species' primary type so
/// every one of the 1025 gets something in character.
enum PetMoveStyle: String, CaseIterable, Equatable {
    case bolt
    case waterJet
    case waterShuriken
    case flameJet
    case ember
    case leafStorm
    case psychicOrb
    case shadowBall
    case darkBurst
    case starBurst
    case coinToss
    case singNotes
    case boneToss
    case rockThrow
    case steelGlint
    case fairySparkle
    case iceShard
    case poisonBubbles
    case gustStreaks
    case dragonPulse
    case auraSphere
    case bugSwarm
    case sandPuff
    case impactBurst
    case dragonDart
    case slashArc
    case mudPuff
    case heartBurst
}

struct PetMove: Equatable {
    let name: String
    let style: PetMoveStyle
}

enum PetMoveCatalog {
    /// Bespoke moves for iconic species. Anything not listed falls back to
    /// its primary type's style, so nobody sits the battle out.
    static let signatures: [Int: PetMove] = [
        1: .init(name: "Vine Whip", style: .leafStorm),
        3: .init(name: "Petal Dance", style: .leafStorm),
        4: .init(name: "Ember", style: .ember),
        6: .init(name: "Flamethrower", style: .flameJet),
        7: .init(name: "Water Gun", style: .waterJet),
        9: .init(name: "Hydro Pump", style: .waterJet),
        12: .init(name: "Sleep Powder", style: .fairySparkle),
        15: .init(name: "Twinneedle", style: .bugSwarm),
        25: .init(name: "Thunderbolt", style: .bolt),
        26: .init(name: "Thunder", style: .bolt),
        39: .init(name: "Sing", style: .singNotes),
        40: .init(name: "Hyper Voice", style: .singNotes),
        52: .init(name: "Pay Day", style: .coinToss),
        53: .init(name: "Pay Day", style: .coinToss),
        68: .init(name: "Dynamic Punch", style: .impactBurst),
        77: .init(name: "Stomp", style: .sandPuff),
        94: .init(name: "Shadow Ball", style: .shadowBall),
        105: .init(name: "Bonemerang", style: .boneToss),
        108: .init(name: "Lick", style: .heartBurst),
        130: .init(name: "Hydro Pump", style: .waterJet),
        131: .init(name: "Ice Beam", style: .iceShard),
        133: .init(name: "Swift", style: .starBurst),
        134: .init(name: "Aurora Beam", style: .iceShard),
        135: .init(name: "Thunderbolt", style: .bolt),
        136: .init(name: "Flamethrower", style: .flameJet),
        143: .init(name: "Yawn", style: .singNotes),
        149: .init(name: "Hyper Beam", style: .dragonPulse),
        150: .init(name: "Psychic", style: .psychicOrb),
        151: .init(name: "Swift", style: .starBurst),
        155: .init(name: "Ember", style: .ember),
        157: .init(name: "Eruption", style: .flameJet),
        158: .init(name: "Water Gun", style: .waterJet),
        160: .init(name: "Hydro Pump", style: .waterJet),
        169: .init(name: "Wing Attack", style: .gustStreaks),
        197: .init(name: "Dark Pulse", style: .darkBurst),
        212: .init(name: "Metal Claw", style: .steelGlint),
        214: .init(name: "Megahorn", style: .impactBurst),
        227: .init(name: "Steel Wing", style: .steelGlint),
        229: .init(name: "Dark Pulse", style: .darkBurst),
        248: .init(name: "Stone Edge", style: .rockThrow),
        249: .init(name: "Aeroblast", style: .gustStreaks),
        250: .init(name: "Sacred Fire", style: .flameJet),
        254: .init(name: "Leaf Blade", style: .slashArc),
        260: .init(name: "Muddy Water", style: .mudPuff),
        282: .init(name: "Psychic", style: .psychicOrb),
        289: .init(name: "Body Slam", style: .impactBurst),
        306: .init(name: "Iron Tail", style: .steelGlint),
        319: .init(name: "Crunch", style: .darkBurst),
        330: .init(name: "Earthquake", style: .sandPuff),
        350: .init(name: "Water Pulse", style: .waterJet),
        359: .init(name: "Shadow Claw", style: .shadowBall),
        373: .init(name: "Dragon Pulse", style: .dragonPulse),
        376: .init(name: "Meteor Mash", style: .steelGlint),
        380: .init(name: "Mist Ball", style: .psychicOrb),
        381: .init(name: "Luster Purge", style: .psychicOrb),
        392: .init(name: "Flare Blitz", style: .flameJet),
        400: .init(name: "Mud Shot", style: .mudPuff),
        423: .init(name: "Muddy Water", style: .mudPuff),
        428: .init(name: "Bounce", style: .heartBurst),
        430: .init(name: "Dark Pulse", style: .darkBurst),
        445: .init(name: "Dragon Claw", style: .dragonPulse),
        448: .init(name: "Aura Sphere", style: .auraSphere),
        460: .init(name: "Wood Hammer", style: .leafStorm),
        461: .init(name: "Night Slash", style: .slashArc),
        468: .init(name: "Dazzling Gleam", style: .fairySparkle),
        471: .init(name: "Ice Beam", style: .iceShard),
        477: .init(name: "Shadow Punch", style: .shadowBall),
        483: .init(name: "Roar of Time", style: .dragonPulse),
        484: .init(name: "Spacial Rend", style: .dragonPulse),
        487: .init(name: "Shadow Force", style: .shadowBall),
        497: .init(name: "Leaf Blade", style: .slashArc),
        500: .init(name: "Flamethrower", style: .flameJet),
        503: .init(name: "Hydro Pump", style: .waterJet),
        530: .init(name: "Drill Run", style: .rockThrow),
        545: .init(name: "Venoshock", style: .poisonBubbles),
        571: .init(name: "Night Daze", style: .darkBurst),
        609: .init(name: "Shadow Ball", style: .shadowBall),
        612: .init(name: "Dragon Pulse", style: .dragonPulse),
        635: .init(name: "Dragon Pulse", style: .dragonPulse),
        637: .init(name: "Fiery Dance", style: .flameJet),
        658: .init(name: "Water Shuriken", style: .waterShuriken),
        663: .init(name: "Brave Bird", style: .gustStreaks),
        681: .init(name: "Sacred Sword", style: .slashArc),
        700: .init(name: "Dazzling Gleam", style: .fairySparkle),
        724: .init(name: "Spirit Shackle", style: .darkBurst),
        727: .init(name: "Darkest Lariat", style: .slashArc),
        730: .init(name: "Sparkling Aria", style: .waterJet),
        734: .init(name: "Brave Bird", style: .gustStreaks),
        784: .init(name: "Clanging Scales", style: .dragonPulse),
        794: .init(name: "Buzz Buzz", style: .bugSwarm),
        800: .init(name: "Photon Geyser", style: .psychicOrb),
        809: .init(name: "Double Iron Bash", style: .steelGlint),
        812: .init(name: "Wood Hammer", style: .leafStorm),
        815: .init(name: "Pyro Ball", style: .ember),
        818: .init(name: "Snipe Shot", style: .waterJet),
        823: .init(name: "Brave Bird", style: .gustStreaks),
        834: .init(name: "Hydro Pump", style: .waterJet),
        845: .init(name: "Dive", style: .waterJet),
        849: .init(name: "Overdrive", style: .bolt),
        861: .init(name: "Spirit Break", style: .fairySparkle),
        873: .init(name: "Icy Wind", style: .iceShard),
        887: .init(name: "Dragon Darts", style: .dragonDart),
        888: .init(name: "Sacred Sword", style: .slashArc),
        889: .init(name: "Behemoth Bash", style: .steelGlint),
        890: .init(name: "Dynamax Cannon", style: .dragonPulse),
        892: .init(name: "Aura Sphere", style: .auraSphere),
        905: .init(name: "Springtide Storm", style: .gustStreaks),
        908: .init(name: "Astonish", style: .shadowBall),
        925: .init(name: "Population Bomb", style: .impactBurst),
        943: .init(name: "Memento", style: .darkBurst),
        959: .init(name: "Psybeam", style: .psychicOrb),
        964: .init(name: "Aqua Step", style: .waterJet),
        967: .init(name: "Sand Attack", style: .sandPuff),
        987: .init(name: "Water Pulse", style: .waterJet),
        994: .init(name: "Fiery Dance", style: .ember),
        1000: .init(name: "Dragon Energy", style: .dragonPulse),
        1007: .init(name: "Electro Shot", style: .bolt),
        1008: .init(name: "Dragon Cheer", style: .dragonPulse),
        1017: .init(name: "Ivy Cudgel", style: .leafStorm),
        2: .init(name: "Razor Leaf", style: .slashArc),
        5: .init(name: "Ember", style: .ember),
        8: .init(name: "Water Gun", style: .waterJet),
        11: .init(name: "Gust", style: .gustStreaks),
        14: .init(name: "Poison Sting", style: .poisonBubbles),
        17: .init(name: "Gust", style: .gustStreaks),
        20: .init(name: "Bite", style: .darkBurst),
        22: .init(name: "Bite", style: .darkBurst),
        24: .init(name: "Poison Fang", style: .poisonBubbles),
        28: .init(name: "Slash", style: .slashArc),
        31: .init(name: "Body Slam", style: .impactBurst),
        33: .init(name: "Poison Jab", style: .poisonBubbles),
        34: .init(name: "Megahorn", style: .impactBurst),
        36: .init(name: "Moonblast", style: .fairySparkle),
        38: .init(name: "Fire Blast", style: .flameJet),
        45: .init(name: "Petal Dance", style: .leafStorm),
        47: .init(name: "Spore", style: .leafStorm),
        55: .init(name: "Hydro Pump", style: .waterJet),
        62: .init(name: "Focus Punch", style: .impactBurst),
        65: .init(name: "Psychic", style: .psychicOrb),
        71: .init(name: "Leaf Blade", style: .slashArc),
        73: .init(name: "Sludge Bomb", style: .poisonBubbles),
        76: .init(name: "Earthquake", style: .sandPuff),
        78: .init(name: "Flame Charge", style: .ember),
        82: .init(name: "Zap Cannon", style: .bolt),
        89: .init(name: "Gunk Shot", style: .poisonBubbles),
        91: .init(name: "Ice Beam", style: .iceShard),
        93: .init(name: "Lick", style: .shadowBall),
        97: .init(name: "Hypnosis", style: .psychicOrb),
        101: .init(name: "Explosion", style: .impactBurst),
        103: .init(name: "Seed Bomb", style: .leafStorm),
        110: .init(name: "Sludge", style: .poisonBubbles),
        112: .init(name: "Horn Drill", style: .rockThrow),
        115: .init(name: "Dizzy Punch", style: .impactBurst),
        117: .init(name: "Bubble Beam", style: .waterJet),
        119: .init(name: "Aqua Tail", style: .waterJet),
        121: .init(name: "Psychic", style: .psychicOrb),
        124: .init(name: "Ice Punch", style: .iceShard),
        125: .init(name: "Thunder Punch", style: .bolt),
        126: .init(name: "Fire Punch", style: .ember),
        137: .init(name: "Tri Attack", style: .bolt),
        139: .init(name: "Rock Slide", style: .rockThrow),
        141: .init(name: "Slash", style: .slashArc),
        153: .init(name: "Magical Leaf", style: .leafStorm),
        156: .init(name: "Flamethrower", style: .flameJet),
        159: .init(name: "Aqua Jet", style: .waterJet),
        162: .init(name: "Hyper Fang", style: .impactBurst),
        166: .init(name: "Comet Punch", style: .impactBurst),
        168: .init(name: "Leech Life", style: .bugSwarm),
        171: .init(name: "Spark", style: .bolt),
        176: .init(name: "Fairy Wind", style: .fairySparkle),
        178: .init(name: "Psybeam", style: .psychicOrb),
        181: .init(name: "Thunder", style: .bolt),
        184: .init(name: "Rollout", style: .rockThrow),
        186: .init(name: "Water Pulse", style: .waterJet),
        189: .init(name: "Cotton Guard", style: .fairySparkle),
        192: .init(name: "Petal Dance", style: .leafStorm),
        195: .init(name: "Mud Shot", style: .mudPuff),
        201: .init(name: "Hidden Power", style: .psychicOrb),
        208: .init(name: "Iron Tail", style: .steelGlint),
        210: .init(name: "Dynamic Punch", style: .impactBurst),
        217: .init(name: "Fury Swipes", style: .slashArc),
        219: .init(name: "Flame Burst", style: .ember),
        221: .init(name: "Blizzard", style: .iceShard),
        222: .init(name: "Rock Blast", style: .rockThrow),
        230: .init(name: "Hydro Pump", style: .waterJet),
        232: .init(name: "Earthquake", style: .sandPuff),
        233: .init(name: "Zap Cannon", style: .bolt),
        237: .init(name: "Hi Jump Kick", style: .impactBurst),
        239: .init(name: "Thunder Punch", style: .bolt),
        240: .init(name: "Fire Punch", style: .ember),
        241: .init(name: "Rock Smash", style: .impactBurst),
        242: .init(name: "Zen Headbutt", style: .psychicOrb),
        244: .init(name: "Flame Wheel", style: .ember),
        246: .init(name: "Bite", style: .darkBurst),
        252: .init(name: "Bullet Seed", style: .leafStorm),
        255: .init(name: "Ember", style: .ember),
        257: .init(name: "Blaze Kick", style: .flameJet),
        258: .init(name: "Water Gun", style: .waterJet),
        259: .init(name: "Mud Shot", style: .mudPuff),
        261: .init(name: "Bite", style: .darkBurst),
        262: .init(name: "Crunch", style: .darkBurst),
        264: .init(name: "Slash", style: .slashArc),
        267: .init(name: "Gust", style: .gustStreaks),
        269: .init(name: "Gust", style: .gustStreaks),
        275: .init(name: "Leaf Storm", style: .leafStorm),
        279: .init(name: "Water Pulse", style: .waterJet),
        284: .init(name: "Bug Buzz", style: .bugSwarm),
        286: .init(name: "Dynamic Punch", style: .impactBurst),
        288: .init(name: "Fury Swipes", style: .slashArc),
        291: .init(name: "Fury Cutter", style: .slashArc),
        297: .init(name: "Brick Break", style: .impactBurst),
        302: .init(name: "Shadow Claw", style: .shadowBall),
        303: .init(name: "Iron Head", style: .steelGlint),
        308: .init(name: "Psychic", style: .psychicOrb),
        310: .init(name: "Thunder", style: .bolt),
        317: .init(name: "Sludge Bomb", style: .poisonBubbles),
        321: .init(name: "Hydro Pump", style: .waterJet),
        323: .init(name: "Earth Power", style: .sandPuff),
        332: .init(name: "Sand Tomb", style: .sandPuff),
        334: .init(name: "Dragon Breath", style: .dragonPulse),
        340: .init(name: "Earthquake", style: .sandPuff),
        344: .init(name: "Psychic", style: .psychicOrb),
        352: .init(name: "Psybeam", style: .psychicOrb),
        355: .init(name: "Shadow Sneak", style: .shadowBall),
        356: .init(name: "Shadow Ball", style: .shadowBall),
        362: .init(name: "Blizzard", style: .iceShard),
        365: .init(name: "Ice Beam", style: .iceShard),
        370: .init(name: "Water Pulse", style: .waterJet),
        372: .init(name: "Dragon Dance", style: .dragonPulse),
        377: .init(name: "Ancient Power", style: .rockThrow),
        378: .init(name: "Blizzard", style: .iceShard),
        379: .init(name: "Thunder", style: .bolt),
        384: .init(name: "Draco Meteor", style: .dragonPulse),
        385: .init(name: "Doom Desire", style: .steelGlint),
        387: .init(name: "Tackle", style: .leafStorm),
        390: .init(name: "Ember", style: .ember),
        391: .init(name: "Flame Wheel", style: .ember),
        393: .init(name: "Bubble", style: .waterJet),
        394: .init(name: "Aqua Jet", style: .waterJet),
        395: .init(name: "Hydro Cannon", style: .waterJet),
        397: .init(name: "Spark", style: .bolt),
        398: .init(name: "Brave Bird", style: .gustStreaks),
        403: .init(name: "Thunder Fang", style: .bolt),
        404: .init(name: "Thunder Fang", style: .bolt),
        405: .init(name: "Discharge", style: .bolt),
        407: .init(name: "Leaf Storm", style: .leafStorm),
        409: .init(name: "Crunch", style: .darkBurst),
        411: .init(name: "Rock Slide", style: .rockThrow),
        416: .init(name: "Attack Order", style: .bugSwarm),
        417: .init(name: "Nuzzle", style: .bolt),
        419: .init(name: "Thunder Fang", style: .bolt),
        422: .init(name: "Mud Bomb", style: .mudPuff),
        427: .init(name: "Bounce", style: .heartBurst),
        429: .init(name: "Shadow Claw", style: .shadowBall),
        432: .init(name: "Pay Day", style: .coinToss),
        435: .init(name: "Sludge Bomb", style: .poisonBubbles),
        437: .init(name: "Psychic", style: .psychicOrb),
        440: .init(name: "Hyper Voice", style: .singNotes),
        441: .init(name: "Chatter", style: .singNotes),
        442: .init(name: "Shadow Ball", style: .shadowBall),
        446: .init(name: "Lick", style: .heartBurst),
        450: .init(name: "Earthquake", style: .sandPuff),
        453: .init(name: "Poison Jab", style: .poisonBubbles),
        454: .init(name: "Poison Jab", style: .poisonBubbles),
        455: .init(name: "Power Whip", style: .leafStorm),
        458: .init(name: "Air Cutter", style: .gustStreaks),
        459: .init(name: "Wood Hammer", style: .leafStorm),
        462: .init(name: "Discharge", style: .bolt),
        464: .init(name: "Earth Power", style: .sandPuff),
        465: .init(name: "Power Whip", style: .leafStorm),
        466: .init(name: "Thunder", style: .bolt),
        467: .init(name: "Flamethrower", style: .flameJet),
        469: .init(name: "Bug Buzz", style: .bugSwarm),
        470: .init(name: "Leaf Blade", style: .slashArc),
        472: .init(name: "Poison Sting", style: .poisonBubbles),
        473: .init(name: "Icicle Crash", style: .iceShard),
        474: .init(name: "Tri Attack", style: .bolt),
        475: .init(name: "Psychic", style: .psychicOrb),
        476: .init(name: "Rock Throw", style: .rockThrow),
        478: .init(name: "Blizzard", style: .iceShard),
        479: .init(name: "Thunder Shock", style: .bolt),
        480: .init(name: "Confusion", style: .psychicOrb),
        481: .init(name: "Confusion", style: .psychicOrb),
        482: .init(name: "Confusion", style: .psychicOrb),
        485: .init(name: "Fire Blast", style: .flameJet),
        486: .init(name: "Earth Power", style: .sandPuff),
        488: .init(name: "Dream Eater", style: .psychicOrb),
        490: .init(name: "Water Pulse", style: .waterJet),
        491: .init(name: "Dark Void", style: .darkBurst),
        492: .init(name: "Seed Flare", style: .leafStorm),
        493: .init(name: "Judgment", style: .starBurst),
        494: .init(name: "V-create", style: .flameJet),
        495: .init(name: "Tackle", style: .leafStorm),
        496: .init(name: "Leaf Blade", style: .slashArc),
        498: .init(name: "Ember", style: .ember),
        499: .init(name: "Flame Burst", style: .ember),
        501: .init(name: "Water Gun", style: .waterJet),
        502: .init(name: "Water Pulse", style: .waterJet),
        505: .init(name: "Hyper Fang", style: .impactBurst),
        508: .init(name: "Crunch", style: .darkBurst),
        510: .init(name: "Night Slash", style: .slashArc),
        513: .init(name: "Flame Burst", style: .ember),
        514: .init(name: "Fire Blast", style: .flameJet),
        517: .init(name: "Hypnosis", style: .psychicOrb),
        518: .init(name: "Dream Eater", style: .psychicOrb),
        523: .init(name: "Signal Beam", style: .bugSwarm),
        531: .init(name: "Drain Punch", style: .impactBurst),
        537: .init(name: "Surf", style: .waterJet),
        542: .init(name: "X-Scissor", style: .slashArc),
        547: .init(name: "Giga Drain", style: .leafStorm),
        551: .init(name: "Bite", style: .darkBurst),
        552: .init(name: "Bite", style: .darkBurst),
        553: .init(name: "Crunch", style: .darkBurst),
        555: .init(name: "Flare Blitz", style: .flameJet),
        556: .init(name: "Sand Attack", style: .sandPuff),
        558: .init(name: "Rock Slide", style: .rockThrow),
        560: .init(name: "Crunch", style: .darkBurst),
        563: .init(name: "Shadow Ball", style: .shadowBall),
        565: .init(name: "Water Pulse", style: .waterJet),
        567: .init(name: "Flame Burst", style: .ember),
        570: .init(name: "Shadow Sneak", style: .shadowBall),
        572: .init(name: "Swift", style: .starBurst),
        575: .init(name: "Psybeam", style: .psychicOrb),
        576: .init(name: "Psychic", style: .psychicOrb),
        577: .init(name: "Confusion", style: .psychicOrb),
        578: .init(name: "Psybeam", style: .psychicOrb),
        579: .init(name: "Psychic", style: .psychicOrb),
        583: .init(name: "Icy Wind", style: .iceShard),
        584: .init(name: "Blizzard", style: .iceShard),
        585: .init(name: "Seed Bomb", style: .leafStorm),
        586: .init(name: "Horn Leech", style: .leafStorm),
        588: .init(name: "Bug Bite", style: .bugSwarm),
        589: .init(name: "Iron Head", style: .steelGlint),
        590: .init(name: "Giga Drain", style: .leafStorm),
        591: .init(name: "Sludge Bomb", style: .poisonBubbles),
        592: .init(name: "Bubble Beam", style: .waterJet),
        593: .init(name: "Shadow Ball", style: .shadowBall),
        594: .init(name: "Heal Pulse", style: .psychicOrb),
        595: .init(name: "Electro Ball", style: .bolt),
        596: .init(name: "Bug Buzz", style: .bugSwarm),
        602: .init(name: "Spark", style: .bolt),
        603: .init(name: "Thunder Fang", style: .bolt),
        604: .init(name: "Discharge", style: .bolt),
        605: .init(name: "Confusion", style: .psychicOrb),
        606: .init(name: "Psybeam", style: .psychicOrb),
        607: .init(name: "Ember", style: .ember),
        608: .init(name: "Flame Burst", style: .ember),
        610: .init(name: "Dragon Rage", style: .dragonPulse),
        611: .init(name: "Dragon Claw", style: .dragonPulse),
        615: .init(name: "Icy Wind", style: .iceShard),
        616: .init(name: "Bug Buzz", style: .bugSwarm),
        618: .init(name: "Mud Bomb", style: .mudPuff),
        620: .init(name: "Aura Sphere", style: .auraSphere),
        621: .init(name: "Dragon Claw", style: .dragonPulse),
        622: .init(name: "Night Shade", style: .darkBurst),
        623: .init(name: "Shadow Punch", style: .shadowBall),
        625: .init(name: "Sacred Sword", style: .slashArc),
        626: .init(name: "Head Charge", style: .impactBurst),
        628: .init(name: "Brave Bird", style: .gustStreaks),
        631: .init(name: "Fire Lash", style: .ember),
        633: .init(name: "Bite", style: .darkBurst),
        634: .init(name: "Dragon Pulse", style: .dragonPulse),
        636: .init(name: "Flame Wheel", style: .ember),
        638: .init(name: "Sacred Sword", style: .slashArc),
        639: .init(name: "Sacred Sword", style: .slashArc),
        640: .init(name: "Sacred Sword", style: .slashArc),
        642: .init(name: "Bolt Strike", style: .bolt),
        643: .init(name: "Blue Flare", style: .flameJet),
        644: .init(name: "Fusion Bolt", style: .bolt),
        645: .init(name: "Fusion Flare", style: .flameJet),
        646: .init(name: "Ice Burn", style: .iceShard),
        647: .init(name: "Secret Sword", style: .slashArc),
        648: .init(name: "Relic Song", style: .singNotes),
        649: .init(name: "Techno Blast", style: .bolt),
        651: .init(name: "Leaf Blade", style: .slashArc),
        652: .init(name: "Leaf Blade", style: .slashArc),
        654: .init(name: "Fire Blast", style: .flameJet),
        655: .init(name: "Moonblast", style: .fairySparkle),
        657: .init(name: "Aqua Jet", style: .waterJet),
        666: .init(name: "Gust", style: .gustStreaks),
        668: .init(name: "Play Nice", style: .fairySparkle),
        671: .init(name: "Petal Dance", style: .leafStorm),
        675: .init(name: "Play Rough", style: .fairySparkle),
        678: .init(name: "Psychic", style: .psychicOrb),
        687: .init(name: "Psychic", style: .psychicOrb),
        694: .init(name: "Psybeam", style: .psychicOrb),
        695: .init(name: "Psychic", style: .psychicOrb),
        696: .init(name: "Rock Throw", style: .rockThrow),
        697: .init(name: "Rock Slide", style: .rockThrow),
        701: .init(name: "Cross Chop", style: .impactBurst),
        703: .init(name: "Power Gem", style: .rockThrow),
        705: .init(name: "Dragon Breath", style: .dragonPulse),
        706: .init(name: "Dragon Pulse", style: .dragonPulse),
        708: .init(name: "Phantom Force", style: .shadowBall),
        709: .init(name: "Shadow Ball", style: .shadowBall),
        711: .init(name: "Avalanche", style: .iceShard),
        712: .init(name: "Icy Wind", style: .iceShard),
        713: .init(name: "Blizzard", style: .iceShard),
        716: .init(name: "Geomancy", style: .fairySparkle),
        719: .init(name: "Diamond Storm", style: .rockThrow),
        720: .init(name: "Hyperspace Hole", style: .shadowBall),
        721: .init(name: "Steam Eruption", style: .waterJet),
        733: .init(name: "Bullet Seed", style: .leafStorm),
        738: .init(name: "Thunderbolt", style: .bolt),
        740: .init(name: "Bone Rush", style: .boneToss),
        742: .init(name: "Bug Bite", style: .bugSwarm),
        743: .init(name: "Pollen Puff", style: .fairySparkle),
        744: .init(name: "Rock Throw", style: .rockThrow),
        745: .init(name: "Continental Crush", style: .rockThrow),
        746: .init(name: "Water Gun", style: .waterJet),
        749: .init(name: "Mud Shot", style: .mudPuff),
        750: .init(name: "High Horsepower", style: .sandPuff),
        752: .init(name: "Liquidation", style: .waterJet),
        753: .init(name: "Fury Cutter", style: .slashArc),
        754: .init(name: "Leaf Storm", style: .leafStorm),
        755: .init(name: "Ember", style: .ember),
        756: .init(name: "Overheat", style: .flameJet),
        757: .init(name: "Fire Fang", style: .ember),
        758: .init(name: "Fiery Dance", style: .flameJet),
        759: .init(name: "Play Rough", style: .fairySparkle),
        760: .init(name: "Cross Chop", style: .impactBurst),
        761: .init(name: "Psychic", style: .psychicOrb),
        762: .init(name: "Psychic", style: .psychicOrb),
        763: .init(name: "Leaf Blade", style: .slashArc),
        764: .init(name: "Moonblast", style: .fairySparkle),
        765: .init(name: "Psychic", style: .psychicOrb),
        766: .init(name: "Close Combat", style: .impactBurst),
        767: .init(name: "Water Gun", style: .waterJet),
        768: .init(name: "Liquidation", style: .waterJet),
        769: .init(name: "Sand Tomb", style: .sandPuff),
        770: .init(name: "Shadow Claw", style: .shadowBall),
        771: .init(name: "Liquidation", style: .waterJet),
        772: .init(name: "Tri Attack", style: .bolt),
        773: .init(name: "Photon Geyser", style: .psychicOrb),
        774: .init(name: "Power Gem", style: .rockThrow),
        775: .init(name: "Rollout", style: .rockThrow),
        776: .init(name: "Rock Wrecker", style: .rockThrow),
        777: .init(name: "Water Gun", style: .waterJet),
        778: .init(name: "Shadow Sneak", style: .shadowBall),
        779: .init(name: "Psychic", style: .psychicOrb),
        780: .init(name: "Dragon Breath", style: .dragonPulse),
        781: .init(name: "Spirit Shackle", style: .darkBurst),
        782: .init(name: "Dragon Breath", style: .dragonPulse),
        783: .init(name: "Clanging Scales", style: .dragonPulse),
        785: .init(name: "Thunderbolt", style: .bolt),
        786: .init(name: "Psychic", style: .psychicOrb),
        789: .init(name: "Cosmic Power", style: .psychicOrb),
        790: .init(name: "Photon Geyser", style: .psychicOrb),
        791: .init(name: "Sunsteel Strike", style: .flameJet),
        792: .init(name: "Moongeist Beam", style: .shadowBall),
        793: .init(name: "Poison Jab", style: .poisonBubbles),
        795: .init(name: "Bug Bite", style: .bugSwarm),
        796: .init(name: "Thunderbolt", style: .bolt),
        797: .init(name: "Behemoth Blade", style: .slashArc),
        798: .init(name: "Ice Beam", style: .iceShard),
        799: .init(name: "Guzzoline", style: .darkBurst),
        801: .init(name: "Flash Cannon", style: .steelGlint),
        802: .init(name: "Shadow Claw", style: .shadowBall),
        804: .init(name: "Dragon Pulse", style: .dragonPulse),
        806: .init(name: "Overheat", style: .flameJet),
        819: .init(name: "Tackle", style: .impactBurst),
        820: .init(name: "Body Slam", style: .impactBurst),
        821: .init(name: "Peck", style: .gustStreaks),
        822: .init(name: "Wing Attack", style: .gustStreaks),
        824: .init(name: "Bug Bite", style: .bugSwarm),
        825: .init(name: "Struggle Bug", style: .bugSwarm),
        826: .init(name: "Pollen Puff", style: .fairySparkle),
        827: .init(name: "Astonish", style: .shadowBall),
        828: .init(name: "Shadow Claw", style: .shadowBall),
        829: .init(name: "Psychic", style: .psychicOrb),
        830: .init(name: "Psychic", style: .psychicOrb),
        831: .init(name: "Double Kick", style: .impactBurst),
        832: .init(name: "Strength", style: .impactBurst),
        833: .init(name: "Tackle", style: .waterJet),
        835: .init(name: "Bite", style: .darkBurst),
        836: .init(name: "Crunch", style: .darkBurst),
        837: .init(name: "Rock Throw", style: .rockThrow),
        838: .init(name: "Rock Slide", style: .rockThrow),
        839: .init(name: "Flamethrower", style: .flameJet),
        840: .init(name: "Branch Poke", style: .leafStorm),
        841: .init(name: "Dragon Dance", style: .leafStorm),
        842: .init(name: "Apple Acid", style: .leafStorm),
        843: .init(name: "Sand Attack", style: .sandPuff),
        844: .init(name: "Rock Slide", style: .rockThrow),
        846: .init(name: "Water Gun", style: .waterJet),
        847: .init(name: "Fishious Rend", style: .waterJet),
        848: .init(name: "Poison Sting", style: .poisonBubbles),
        850: .init(name: "Fire Fang", style: .ember),
        851: .init(name: "Fire Lash", style: .ember),
        852: .init(name: "Rock Smash", style: .impactBurst),
        853: .init(name: "Iron Head", style: .steelGlint),
        854: .init(name: "Hex", style: .shadowBall),
        856: .init(name: "Confusion", style: .psychicOrb),
        857: .init(name: "Psybeam", style: .psychicOrb),
        858: .init(name: "Psychic", style: .psychicOrb),
        859: .init(name: "Astonish", style: .shadowBall),
        860: .init(name: "Spirit Break", style: .fairySparkle),
        862: .init(name: "Crunch", style: .darkBurst),
        863: .init(name: "Iron Head", style: .steelGlint),
        864: .init(name: "Psychic", style: .psychicOrb),
        865: .init(name: "Yawn", style: .singNotes),
        866: .init(name: "Moonblast", style: .fairySparkle),
        867: .init(name: "Shadow Ball", style: .shadowBall),
        868: .init(name: "Sugar Rush", style: .fairySparkle),
        869: .init(name: "Draining Kiss", style: .fairySparkle),
        870: .init(name: "Rock Throw", style: .rockThrow),
        871: .init(name: "Thunder Wave", style: .bolt),
        872: .init(name: "Icicle Spear", style: .iceShard),
        874: .init(name: "Rock Throw", style: .rockThrow),
        875: .init(name: "Icicle Crash", style: .iceShard),
        876: .init(name: "Psychic", style: .psychicOrb),
        877: .init(name: "Play Rough", style: .fairySparkle),
        880: .init(name: "Thunderbolt", style: .bolt),
        881: .init(name: "Ice Beam", style: .iceShard),
        882: .init(name: "Draco Meteor", style: .dragonPulse),
        883: .init(name: "Ice Beam", style: .iceShard),
        884: .init(name: "Draco Meteor", style: .dragonPulse),
        885: .init(name: "Dragon Breath", style: .dragonPulse),
        886: .init(name: "Dragon Claw", style: .dragonPulse),
        893: .init(name: "Ivy Cudgel", style: .darkBurst),
        895: .init(name: "Glaive Rush", style: .dragonPulse),
        896: .init(name: "Glacial Lance", style: .iceShard),
        897: .init(name: "Astral Barrage", style: .shadowBall),
        898: .init(name: "Behemoth Blade", style: .slashArc),
        900: .init(name: "Volt Switch", style: .bolt),
        901: .init(name: "Giga Impact", style: .impactBurst),
        902: .init(name: "Aqua Step", style: .waterJet),
        903: .init(name: "Sacred Sword", style: .slashArc),
        904: .init(name: "Moonblast", style: .fairySparkle),
        907: .init(name: "Flame Wheel", style: .ember),
        910: .init(name: "Aqua Cutter", style: .waterJet),
        911: .init(name: "Aqua Step", style: .waterJet),
        913: .init(name: "Flame Charge", style: .ember),
        914: .init(name: "Blaze Kick", style: .flameJet),
        915: .init(name: "Electro Ball", style: .bolt),
        916: .init(name: "Earth Power", style: .sandPuff),
        917: .init(name: "Astonish", style: .shadowBall),
        918: .init(name: "Sparkling Aria", style: .waterJet),
        919: .init(name: "Water Pulse", style: .waterJet),
        920: .init(name: "Aqua Step", style: .waterJet),
        921: .init(name: "Bite", style: .darkBurst),
        922: .init(name: "Psychic", style: .psychicOrb),
        923: .init(name: "Psychic", style: .psychicOrb),
        924: .init(name: "Bite", style: .darkBurst),
        926: .init(name: "Sand Attack", style: .sandPuff),
        927: .init(name: "Tackle", style: .impactBurst),
        928: .init(name: "Strength", style: .impactBurst),
        929: .init(name: "Tail Whip", style: .heartBurst),
        930: .init(name: "Dark Pulse", style: .darkBurst),
        931: .init(name: "Night Shade", style: .darkBurst),
        932: .init(name: "Sand Tomb", style: .sandPuff),
        933: .init(name: "Earth Power", style: .sandPuff),
        934: .init(name: "Surf", style: .waterJet),
        935: .init(name: "Poison Fang", style: .poisonBubbles),
        936: .init(name: "Mud Shot", style: .mudPuff),
        937: .init(name: "Earth Power", style: .sandPuff),
        938: .init(name: "Rock Throw", style: .rockThrow),
        939: .init(name: "Flamethrower", style: .flameJet),
        940: .init(name: "Bite", style: .darkBurst),
        941: .init(name: "Wing Attack", style: .gustStreaks),
        942: .init(name: "Crunch", style: .darkBurst),
        944: .init(name: "Double Kick", style: .impactBurst),
        945: .init(name: "Aerial Ace", style: .gustStreaks),
        946: .init(name: "Psybeam", style: .psychicOrb),
        947: .init(name: "Psychic", style: .psychicOrb),
        948: .init(name: "Poison Sting", style: .poisonBubbles),
        949: .init(name: "Toxic Spikes", style: .poisonBubbles),
        950: .init(name: "Barb Barrage", style: .poisonBubbles),
        951: .init(name: "Rock Throw", style: .rockThrow),
        952: .init(name: "Leaf Blade", style: .slashArc),
        953: .init(name: "Flower Trick", style: .leafStorm),
        954: .init(name: "Recover", style: .psychicOrb),
        955: .init(name: "Sparkling Aria", style: .waterJet),
        956: .init(name: "Psybeam", style: .psychicOrb),
        957: .init(name: "Psychic", style: .psychicOrb),
        958: .init(name: "Shadow Ball", style: .shadowBall),
        960: .init(name: "Earth Power", style: .sandPuff),
        961: .init(name: "Psychic", style: .psychicOrb),
        962: .init(name: "Crunch", style: .darkBurst),
        963: .init(name: "Aqua Cutter", style: .waterJet),
        965: .init(name: "Mud Shot", style: .mudPuff),
        966: .init(name: "Rock Throw", style: .rockThrow),
        970: .init(name: "Flame Wheel", style: .ember),
        971: .init(name: "Confusion", style: .psychicOrb),
        972: .init(name: "Snowscape", style: .iceShard),
        973: .init(name: "Aurora Beam", style: .iceShard),
        974: .init(name: "Rock Throw", style: .rockThrow),
        975: .init(name: "Steel Beam", style: .steelGlint),
        976: .init(name: "Water Pulse", style: .waterJet),
        977: .init(name: "Bite", style: .darkBurst),
        978: .init(name: "Psybeam", style: .psychicOrb),
        979: .init(name: "Shadow Claw", style: .shadowBall),
        980: .init(name: "Draco Meteor", style: .dragonPulse),
        981: .init(name: "Ice Spinner", style: .iceShard),
        982: .init(name: "Psychic Noise", style: .psychicOrb),
        983: .init(name: "Iron Head", style: .steelGlint),
        984: .init(name: "Snowscape", style: .iceShard),
        985: .init(name: "Rock Slide", style: .rockThrow),
        986: .init(name: "Thunder Fang", style: .bolt),
        988: .init(name: "Screech", style: .darkBurst),
        989: .init(name: "Rubble Trouble", style: .rockThrow),
        990: .init(name: "Iron Head", style: .steelGlint),
        991: .init(name: "Aero Blast", style: .gustStreaks),
        992: .init(name: "Poison Jab", style: .poisonBubbles),
        993: .init(name: "Dragon Pulse", style: .dragonPulse),
        995: .init(name: "Thunder Fang", style: .bolt),
        996: .init(name: "Icy Wind", style: .iceShard),
        997: .init(name: "Dragon Breath", style: .dragonPulse),
        998: .init(name: "Ice Blade", style: .iceShard),
        999: .init(name: "Dark Pulse", style: .darkBurst),
        1001: .init(name: "Head Charge", style: .darkBurst),
        1002: .init(name: "Grassy Glide", style: .leafStorm),
        1003: .init(name: "Blizzard", style: .iceShard),
        1004: .init(name: "Flame Charge", style: .ember),
        1005: .init(name: "Roar of Time", style: .dragonPulse),
        1006: .init(name: "Hydro Steam", style: .waterJet),
        1009: .init(name: "Wandering Spirit", style: .shadowBall),
        1010: .init(name: "Psyblade", style: .slashArc),
        1011: .init(name: "Wood Hammer", style: .leafStorm),
        1012: .init(name: "Pounce", style: .bugSwarm),
        1013: .init(name: "Population Bomb", style: .impactBurst),
        1014: .init(name: "Hustle", style: .bugSwarm),
        1015: .init(name: "Dragon Pulse", style: .dragonPulse),
        1016: .init(name: "Toxic Spikes", style: .poisonBubbles),
        1018: .init(name: "Struggle Bug", style: .waterJet),
        1019: .init(name: "Seed Flare", style: .leafStorm),
        1020: .init(name: "Gold Rush", style: .coinToss),
        1021: .init(name: "Bundle", style: .bolt),
        1022: .init(name: "Iron Head", style: .steelGlint),
        1023: .init(name: "Raging Bull", style: .impactBurst),
        1025: .init(name: "Tera Starstorm", style: .starBurst),
    ]

    /// The species' move: signature first, then primary type, then a plain
    /// star burst so even typeless stragglers perform.
    static func move(for dexID: Int, types: String?) -> PetMove {
        if let signature = signatures[dexID] { return signature }
        let primary = types?
            .split(separator: "·")
            .first
            .flatMap { $0.trimmingCharacters(in: .whitespaces) }
        if let primary, !primary.isEmpty {
            return PetMove(name: "\(primary) move", style: style(forType: primary))
        }
        return PetMove(name: "Swift", style: .starBurst)
    }

    /// Type word → particle style. Matching is case-insensitive on the type
    /// identifier as it appears in the catalog's type column.
    static func style(forType type: String) -> PetMoveStyle {
        switch type.lowercased() {
        case "water": return .waterJet
        case "fire": return .ember
        case "grass": return .leafStorm
        case "electric": return .bolt
        case "ice": return .iceShard
        case "psychic": return .psychicOrb
        case "ghost": return .shadowBall
        case "dark": return .darkBurst
        case "dragon": return .dragonPulse
        case "steel": return .steelGlint
        case "fairy": return .fairySparkle
        case "poison": return .poisonBubbles
        case "fighting": return .impactBurst
        case "rock": return .rockThrow
        case "ground": return .sandPuff
        case "flying": return .gustStreaks
        case "bug": return .bugSwarm
        default: return .starBurst
        }
    }
}
