// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 chuahchengxi

// Generated by Tools/gen-species-catalog.py from the PokeAPI CSV dumps.
// The full National Dex, one line per species:
// id|Name|Types|nextEvolutionID|captureRate.
// Parsed at first use rather than written as struct literals, which the
// Swift type checker takes minutes to chew through at this size.

let speciesCatalogData = """
1|Bulbasaur|Grass · Poison|2|45
2|Ivysaur|Grass · Poison|3|45
3|Venusaur|Grass · Poison||45
4|Charmander|Fire|5|45
5|Charmeleon|Fire|6|45
6|Charizard|Fire · Flying||45
7|Squirtle|Water|8|45
8|Wartortle|Water|9|45
9|Blastoise|Water||45
10|Caterpie|Bug|11|255
11|Metapod|Bug|12|120
12|Butterfree|Bug · Flying||45
13|Weedle|Bug · Poison|14|255
14|Kakuna|Bug · Poison|15|120
15|Beedrill|Bug · Poison||45
16|Pidgey|Normal · Flying|17|255
17|Pidgeotto|Normal · Flying|18|120
18|Pidgeot|Normal · Flying||45
19|Rattata|Normal|20|255
20|Raticate|Normal||127
21|Spearow|Normal · Flying|22|255
22|Fearow|Normal · Flying||90
23|Ekans|Poison|24|255
24|Arbok|Poison||90
25|Pikachu|Electric|26|190
26|Raichu|Electric||75
27|Sandshrew|Ground|28|255
28|Sandslash|Ground||90
29|Nidoran♀|Poison|30|235
30|Nidorina|Poison|31|120
31|Nidoqueen|Poison · Ground||45
32|Nidoran♂|Poison|33|235
33|Nidorino|Poison|34|120
34|Nidoking|Poison · Ground||45
35|Clefairy|Fairy|36|150
36|Clefable|Fairy||25
37|Vulpix|Fire|38|190
38|Ninetales|Fire||75
39|Jigglypuff|Normal · Fairy|40|170
40|Wigglytuff|Normal · Fairy||50
41|Zubat|Poison · Flying|42|255
42|Golbat|Poison · Flying|169|90
43|Oddish|Grass · Poison|44|255
44|Gloom|Grass · Poison|45|120
45|Vileplume|Grass · Poison||45
46|Paras|Bug · Grass|47|190
47|Parasect|Bug · Grass||75
48|Venonat|Bug · Poison|49|190
49|Venomoth|Bug · Poison||75
50|Diglett|Ground|51|255
51|Dugtrio|Ground||50
52|Meowth|Normal|53|255
53|Persian|Normal||90
54|Psyduck|Water|55|190
55|Golduck|Water||75
56|Mankey|Fighting|57|190
57|Primeape|Fighting|979|75
58|Growlithe|Fire|59|190
59|Arcanine|Fire||75
60|Poliwag|Water|61|255
61|Poliwhirl|Water|62|120
62|Poliwrath|Water · Fighting||45
63|Abra|Psychic|64|200
64|Kadabra|Psychic|65|100
65|Alakazam|Psychic||50
66|Machop|Fighting|67|180
67|Machoke|Fighting|68|90
68|Machamp|Fighting||45
69|Bellsprout|Grass · Poison|70|255
70|Weepinbell|Grass · Poison|71|120
71|Victreebel|Grass · Poison||45
72|Tentacool|Water · Poison|73|190
73|Tentacruel|Water · Poison||60
74|Geodude|Rock · Ground|75|255
75|Graveler|Rock · Ground|76|120
76|Golem|Rock · Ground||45
77|Ponyta|Fire|78|190
78|Rapidash|Fire||60
79|Slowpoke|Water · Psychic|80|190
80|Slowbro|Water · Psychic||75
81|Magnemite|Electric · Steel|82|190
82|Magneton|Electric · Steel|462|60
83|Farfetch’d|Normal · Flying|865|45
84|Doduo|Normal · Flying|85|190
85|Dodrio|Normal · Flying||45
86|Seel|Water|87|190
87|Dewgong|Water · Ice||75
88|Grimer|Poison|89|190
89|Muk|Poison||75
90|Shellder|Water|91|190
91|Cloyster|Water · Ice||60
92|Gastly|Ghost · Poison|93|190
93|Haunter|Ghost · Poison|94|90
94|Gengar|Ghost · Poison||45
95|Onix|Rock · Ground|208|45
96|Drowzee|Psychic|97|190
97|Hypno|Psychic||75
98|Krabby|Water|99|225
99|Kingler|Water||60
100|Voltorb|Electric|101|190
101|Electrode|Electric||60
102|Exeggcute|Grass · Psychic|103|90
103|Exeggutor|Grass · Psychic||45
104|Cubone|Ground|105|190
105|Marowak|Ground||75
106|Hitmonlee|Fighting||45
107|Hitmonchan|Fighting||45
108|Lickitung|Normal|463|45
109|Koffing|Poison|110|190
110|Weezing|Poison||60
111|Rhyhorn|Ground · Rock|112|120
112|Rhydon|Ground · Rock|464|60
113|Chansey|Normal|242|30
114|Tangela|Grass|465|45
115|Kangaskhan|Normal||45
116|Horsea|Water|117|225
117|Seadra|Water|230|75
118|Goldeen|Water|119|225
119|Seaking|Water||60
120|Staryu|Water|121|225
121|Starmie|Water · Psychic||60
122|Mr. Mime|Psychic · Fairy|866|45
123|Scyther|Bug · Flying|212|45
124|Jynx|Ice · Psychic||45
125|Electabuzz|Electric|466|45
126|Magmar|Fire|467|45
127|Pinsir|Bug||45
128|Tauros|Normal||45
129|Magikarp|Water|130|255
130|Gyarados|Water · Flying||45
131|Lapras|Water · Ice||45
132|Ditto|Normal||35
133|Eevee|Normal|134|45
134|Vaporeon|Water||45
135|Jolteon|Electric||45
136|Flareon|Fire||45
137|Porygon|Normal|233|45
138|Omanyte|Rock · Water|139|45
139|Omastar|Rock · Water||45
140|Kabuto|Rock · Water|141|45
141|Kabutops|Rock · Water||45
142|Aerodactyl|Rock · Flying||45
143|Snorlax|Normal||25
144|Articuno|Ice · Flying||3
145|Zapdos|Electric · Flying||3
146|Moltres|Fire · Flying||3
147|Dratini|Dragon|148|45
148|Dragonair|Dragon|149|45
149|Dragonite|Dragon · Flying||45
150|Mewtwo|Psychic||3
151|Mew|Psychic||45
152|Chikorita|Grass|153|45
153|Bayleef|Grass|154|45
154|Meganium|Grass||45
155|Cyndaquil|Fire|156|45
156|Quilava|Fire|157|45
157|Typhlosion|Fire||45
158|Totodile|Water|159|45
159|Croconaw|Water|160|45
160|Feraligatr|Water||45
161|Sentret|Normal|162|255
162|Furret|Normal||90
163|Hoothoot|Normal · Flying|164|255
164|Noctowl|Normal · Flying||90
165|Ledyba|Bug · Flying|166|255
166|Ledian|Bug · Flying||90
167|Spinarak|Bug · Poison|168|255
168|Ariados|Bug · Poison||90
169|Crobat|Poison · Flying||90
170|Chinchou|Water · Electric|171|190
171|Lanturn|Water · Electric||75
172|Pichu|Electric|25|190
173|Cleffa|Fairy|35|150
174|Igglybuff|Normal · Fairy|39|170
175|Togepi|Fairy|176|190
176|Togetic|Fairy · Flying|468|75
177|Natu|Psychic · Flying|178|190
178|Xatu|Psychic · Flying||75
179|Mareep|Electric|180|235
180|Flaaffy|Electric|181|120
181|Ampharos|Electric||45
182|Bellossom|Grass||45
183|Marill|Water · Fairy|184|190
184|Azumarill|Water · Fairy||75
185|Sudowoodo|Rock||65
186|Politoed|Water||45
187|Hoppip|Grass · Flying|188|255
188|Skiploom|Grass · Flying|189|120
189|Jumpluff|Grass · Flying||45
190|Aipom|Normal|424|45
191|Sunkern|Grass|192|235
192|Sunflora|Grass||120
193|Yanma|Bug · Flying|469|75
194|Wooper|Water · Ground|195|255
195|Quagsire|Water · Ground||90
196|Espeon|Psychic||45
197|Umbreon|Dark||45
198|Murkrow|Dark · Flying|430|30
199|Slowking|Water · Psychic||70
200|Misdreavus|Ghost|429|45
201|Unown|Psychic||225
202|Wobbuffet|Psychic||45
203|Girafarig|Normal · Psychic|981|60
204|Pineco|Bug|205|190
205|Forretress|Bug · Steel||75
206|Dunsparce|Normal|982|190
207|Gligar|Ground · Flying|472|60
208|Steelix|Steel · Ground||25
209|Snubbull|Fairy|210|190
210|Granbull|Fairy||75
211|Qwilfish|Water · Poison|904|45
212|Scizor|Bug · Steel||25
213|Shuckle|Bug · Rock||190
214|Heracross|Bug · Fighting||45
215|Sneasel|Dark · Ice|461|60
216|Teddiursa|Normal|217|120
217|Ursaring|Normal|901|60
218|Slugma|Fire|219|190
219|Magcargo|Fire · Rock||75
220|Swinub|Ice · Ground|221|225
221|Piloswine|Ice · Ground|473|75
222|Corsola|Water · Rock|864|60
223|Remoraid|Water|224|190
224|Octillery|Water||75
225|Delibird|Ice · Flying||45
226|Mantine|Water · Flying||25
227|Skarmory|Steel · Flying||25
228|Houndour|Dark · Fire|229|120
229|Houndoom|Dark · Fire||45
230|Kingdra|Water · Dragon||45
231|Phanpy|Ground|232|120
232|Donphan|Ground||60
233|Porygon2|Normal|474|45
234|Stantler|Normal|899|45
235|Smeargle|Normal||45
236|Tyrogue|Fighting|106|75
237|Hitmontop|Fighting||45
238|Smoochum|Ice · Psychic|124|45
239|Elekid|Electric|125|45
240|Magby|Fire|126|45
241|Miltank|Normal||45
242|Blissey|Normal||30
243|Raikou|Electric||3
244|Entei|Fire||3
245|Suicune|Water||3
246|Larvitar|Rock · Ground|247|45
247|Pupitar|Rock · Ground|248|45
248|Tyranitar|Rock · Dark||45
249|Lugia|Psychic · Flying||3
250|Ho-Oh|Fire · Flying||3
251|Celebi|Psychic · Grass||45
252|Treecko|Grass|253|45
253|Grovyle|Grass|254|45
254|Sceptile|Grass||45
255|Torchic|Fire|256|45
256|Combusken|Fire · Fighting|257|45
257|Blaziken|Fire · Fighting||45
258|Mudkip|Water|259|45
259|Marshtomp|Water · Ground|260|45
260|Swampert|Water · Ground||45
261|Poochyena|Dark|262|255
262|Mightyena|Dark||127
263|Zigzagoon|Normal|264|255
264|Linoone|Normal|862|90
265|Wurmple|Bug|266|255
266|Silcoon|Bug|267|120
267|Beautifly|Bug · Flying||45
268|Cascoon|Bug|269|120
269|Dustox|Bug · Poison||45
270|Lotad|Water · Grass|271|255
271|Lombre|Water · Grass|272|120
272|Ludicolo|Water · Grass||45
273|Seedot|Grass|274|255
274|Nuzleaf|Grass · Dark|275|120
275|Shiftry|Grass · Dark||45
276|Taillow|Normal · Flying|277|200
277|Swellow|Normal · Flying||45
278|Wingull|Water · Flying|279|190
279|Pelipper|Water · Flying||45
280|Ralts|Psychic · Fairy|281|235
281|Kirlia|Psychic · Fairy|282|120
282|Gardevoir|Psychic · Fairy||45
283|Surskit|Bug · Water|284|200
284|Masquerain|Bug · Flying||75
285|Shroomish|Grass|286|255
286|Breloom|Grass · Fighting||90
287|Slakoth|Normal|288|255
288|Vigoroth|Normal|289|120
289|Slaking|Normal||45
290|Nincada|Bug · Ground|291|255
291|Ninjask|Bug · Flying||120
292|Shedinja|Bug · Ghost||45
293|Whismur|Normal|294|190
294|Loudred|Normal|295|120
295|Exploud|Normal||45
296|Makuhita|Fighting|297|180
297|Hariyama|Fighting||200
298|Azurill|Normal · Fairy|183|150
299|Nosepass|Rock|476|255
300|Skitty|Normal|301|255
301|Delcatty|Normal||60
302|Sableye|Dark · Ghost||45
303|Mawile|Steel · Fairy||45
304|Aron|Steel · Rock|305|180
305|Lairon|Steel · Rock|306|90
306|Aggron|Steel · Rock||45
307|Meditite|Fighting · Psychic|308|180
308|Medicham|Fighting · Psychic||90
309|Electrike|Electric|310|120
310|Manectric|Electric||45
311|Plusle|Electric||200
312|Minun|Electric||200
313|Volbeat|Bug||150
314|Illumise|Bug||150
315|Roselia|Grass · Poison|407|150
316|Gulpin|Poison|317|225
317|Swalot|Poison||75
318|Carvanha|Water · Dark|319|225
319|Sharpedo|Water · Dark||60
320|Wailmer|Water|321|125
321|Wailord|Water||60
322|Numel|Fire · Ground|323|255
323|Camerupt|Fire · Ground||150
324|Torkoal|Fire||90
325|Spoink|Psychic|326|255
326|Grumpig|Psychic||60
327|Spinda|Normal||255
328|Trapinch|Ground|329|255
329|Vibrava|Ground · Dragon|330|120
330|Flygon|Ground · Dragon||45
331|Cacnea|Grass|332|190
332|Cacturne|Grass · Dark||60
333|Swablu|Normal · Flying|334|255
334|Altaria|Dragon · Flying||45
335|Zangoose|Normal||90
336|Seviper|Poison||90
337|Lunatone|Rock · Psychic||45
338|Solrock|Rock · Psychic||45
339|Barboach|Water · Ground|340|190
340|Whiscash|Water · Ground||75
341|Corphish|Water|342|205
342|Crawdaunt|Water · Dark||155
343|Baltoy|Ground · Psychic|344|255
344|Claydol|Ground · Psychic||90
345|Lileep|Rock · Grass|346|45
346|Cradily|Rock · Grass||45
347|Anorith|Rock · Bug|348|45
348|Armaldo|Rock · Bug||45
349|Feebas|Water|350|255
350|Milotic|Water||60
351|Castform|Normal||45
352|Kecleon|Normal||200
353|Shuppet|Ghost|354|225
354|Banette|Ghost||45
355|Duskull|Ghost|356|190
356|Dusclops|Ghost|477|90
357|Tropius|Grass · Flying||200
358|Chimecho|Psychic||45
359|Absol|Dark||30
360|Wynaut|Psychic|202|125
361|Snorunt|Ice|362|190
362|Glalie|Ice||75
363|Spheal|Ice · Water|364|255
364|Sealeo|Ice · Water|365|120
365|Walrein|Ice · Water||45
366|Clamperl|Water|367|255
367|Huntail|Water||60
368|Gorebyss|Water||60
369|Relicanth|Water · Rock||25
370|Luvdisc|Water||225
371|Bagon|Dragon|372|45
372|Shelgon|Dragon|373|45
373|Salamence|Dragon · Flying||45
374|Beldum|Steel · Psychic|375|3
375|Metang|Steel · Psychic|376|3
376|Metagross|Steel · Psychic||3
377|Regirock|Rock||3
378|Regice|Ice||3
379|Registeel|Steel||3
380|Latias|Dragon · Psychic||3
381|Latios|Dragon · Psychic||3
382|Kyogre|Water||3
383|Groudon|Ground||3
384|Rayquaza|Dragon · Flying||45
385|Jirachi|Steel · Psychic||3
386|Deoxys|Psychic||3
387|Turtwig|Grass|388|45
388|Grotle|Grass|389|45
389|Torterra|Grass · Ground||45
390|Chimchar|Fire|391|45
391|Monferno|Fire · Fighting|392|45
392|Infernape|Fire · Fighting||45
393|Piplup|Water|394|45
394|Prinplup|Water|395|45
395|Empoleon|Water · Steel||45
396|Starly|Normal · Flying|397|255
397|Staravia|Normal · Flying|398|120
398|Staraptor|Normal · Flying||45
399|Bidoof|Normal|400|255
400|Bibarel|Normal · Water||127
401|Kricketot|Bug|402|255
402|Kricketune|Bug||45
403|Shinx|Electric|404|235
404|Luxio|Electric|405|120
405|Luxray|Electric||45
406|Budew|Grass · Poison|315|255
407|Roserade|Grass · Poison||75
408|Cranidos|Rock|409|45
409|Rampardos|Rock||45
410|Shieldon|Rock · Steel|411|45
411|Bastiodon|Rock · Steel||45
412|Burmy|Bug|413|120
413|Wormadam|Bug · Grass||45
414|Mothim|Bug · Flying||45
415|Combee|Bug · Flying|416|120
416|Vespiquen|Bug · Flying||45
417|Pachirisu|Electric||200
418|Buizel|Water|419|190
419|Floatzel|Water||75
420|Cherubi|Grass|421|190
421|Cherrim|Grass||75
422|Shellos|Water|423|190
423|Gastrodon|Water · Ground||75
424|Ambipom|Normal||45
425|Drifloon|Ghost · Flying|426|125
426|Drifblim|Ghost · Flying||60
427|Buneary|Normal|428|190
428|Lopunny|Normal||60
429|Mismagius|Ghost||45
430|Honchkrow|Dark · Flying||30
431|Glameow|Normal|432|190
432|Purugly|Normal||75
433|Chingling|Psychic|358|120
434|Stunky|Poison · Dark|435|225
435|Skuntank|Poison · Dark||60
436|Bronzor|Steel · Psychic|437|255
437|Bronzong|Steel · Psychic||90
438|Bonsly|Rock|185|255
439|Mime Jr.|Psychic · Fairy|122|145
440|Happiny|Normal|113|130
441|Chatot|Normal · Flying||30
442|Spiritomb|Ghost · Dark||100
443|Gible|Dragon · Ground|444|45
444|Gabite|Dragon · Ground|445|45
445|Garchomp|Dragon · Ground||45
446|Munchlax|Normal|143|50
447|Riolu|Fighting|448|75
448|Lucario|Fighting · Steel||45
449|Hippopotas|Ground|450|140
450|Hippowdon|Ground||60
451|Skorupi|Poison · Bug|452|120
452|Drapion|Poison · Dark||45
453|Croagunk|Poison · Fighting|454|140
454|Toxicroak|Poison · Fighting||75
455|Carnivine|Grass||200
456|Finneon|Water|457|190
457|Lumineon|Water||75
458|Mantyke|Water · Flying|226|25
459|Snover|Grass · Ice|460|120
460|Abomasnow|Grass · Ice||60
461|Weavile|Dark · Ice||45
462|Magnezone|Electric · Steel||30
463|Lickilicky|Normal||30
464|Rhyperior|Ground · Rock||30
465|Tangrowth|Grass||30
466|Electivire|Electric||30
467|Magmortar|Fire||30
468|Togekiss|Fairy · Flying||30
469|Yanmega|Bug · Flying||30
470|Leafeon|Grass||45
471|Glaceon|Ice||45
472|Gliscor|Ground · Flying||30
473|Mamoswine|Ice · Ground||50
474|Porygon-Z|Normal||30
475|Gallade|Psychic · Fighting||45
476|Probopass|Rock · Steel||60
477|Dusknoir|Ghost||45
478|Froslass|Ice · Ghost||75
479|Rotom|Electric · Ghost||45
480|Uxie|Psychic||3
481|Mesprit|Psychic||3
482|Azelf|Psychic||3
483|Dialga|Steel · Dragon||3
484|Palkia|Water · Dragon||3
485|Heatran|Fire · Steel||3
486|Regigigas|Normal||3
487|Giratina|Ghost · Dragon||3
488|Cresselia|Psychic||3
489|Phione|Water||30
490|Manaphy|Water||3
491|Darkrai|Dark||3
492|Shaymin|Grass||45
493|Arceus|Normal||3
494|Victini|Psychic · Fire||3
495|Snivy|Grass|496|45
496|Servine|Grass|497|45
497|Serperior|Grass||45
498|Tepig|Fire|499|45
499|Pignite|Fire · Fighting|500|45
500|Emboar|Fire · Fighting||45
501|Oshawott|Water|502|45
502|Dewott|Water|503|45
503|Samurott|Water||45
504|Patrat|Normal|505|255
505|Watchog|Normal||255
506|Lillipup|Normal|507|255
507|Herdier|Normal|508|120
508|Stoutland|Normal||45
509|Purrloin|Dark|510|255
510|Liepard|Dark||90
511|Pansage|Grass|512|190
512|Simisage|Grass||75
513|Pansear|Fire|514|190
514|Simisear|Fire||75
515|Panpour|Water|516|190
516|Simipour|Water||75
517|Munna|Psychic|518|190
518|Musharna|Psychic||75
519|Pidove|Normal · Flying|520|255
520|Tranquill|Normal · Flying|521|120
521|Unfezant|Normal · Flying||45
522|Blitzle|Electric|523|190
523|Zebstrika|Electric||75
524|Roggenrola|Rock|525|255
525|Boldore|Rock|526|120
526|Gigalith|Rock||45
527|Woobat|Psychic · Flying|528|190
528|Swoobat|Psychic · Flying||45
529|Drilbur|Ground|530|120
530|Excadrill|Ground · Steel||60
531|Audino|Normal||255
532|Timburr|Fighting|533|180
533|Gurdurr|Fighting|534|90
534|Conkeldurr|Fighting||45
535|Tympole|Water|536|255
536|Palpitoad|Water · Ground|537|120
537|Seismitoad|Water · Ground||45
538|Throh|Fighting||45
539|Sawk|Fighting||45
540|Sewaddle|Bug · Grass|541|255
541|Swadloon|Bug · Grass|542|120
542|Leavanny|Bug · Grass||45
543|Venipede|Bug · Poison|544|255
544|Whirlipede|Bug · Poison|545|120
545|Scolipede|Bug · Poison||45
546|Cottonee|Grass · Fairy|547|190
547|Whimsicott|Grass · Fairy||75
548|Petilil|Grass|549|190
549|Lilligant|Grass||75
550|Basculin|Water|902|25
551|Sandile|Ground · Dark|552|180
552|Krokorok|Ground · Dark|553|90
553|Krookodile|Ground · Dark||45
554|Darumaka|Fire|555|120
555|Darmanitan|Fire||60
556|Maractus|Grass||255
557|Dwebble|Bug · Rock|558|190
558|Crustle|Bug · Rock||75
559|Scraggy|Dark · Fighting|560|180
560|Scrafty|Dark · Fighting||90
561|Sigilyph|Psychic · Flying||45
562|Yamask|Ghost|563|190
563|Cofagrigus|Ghost||90
564|Tirtouga|Water · Rock|565|45
565|Carracosta|Water · Rock||45
566|Archen|Rock · Flying|567|45
567|Archeops|Rock · Flying||45
568|Trubbish|Poison|569|190
569|Garbodor|Poison||60
570|Zorua|Dark|571|75
571|Zoroark|Dark||45
572|Minccino|Normal|573|255
573|Cinccino|Normal||60
574|Gothita|Psychic|575|200
575|Gothorita|Psychic|576|100
576|Gothitelle|Psychic||50
577|Solosis|Psychic|578|200
578|Duosion|Psychic|579|100
579|Reuniclus|Psychic||50
580|Ducklett|Water · Flying|581|190
581|Swanna|Water · Flying||45
582|Vanillite|Ice|583|255
583|Vanillish|Ice|584|120
584|Vanilluxe|Ice||45
585|Deerling|Normal · Grass|586|190
586|Sawsbuck|Normal · Grass||75
587|Emolga|Electric · Flying||200
588|Karrablast|Bug|589|200
589|Escavalier|Bug · Steel||75
590|Foongus|Grass · Poison|591|190
591|Amoonguss|Grass · Poison||75
592|Frillish|Water · Ghost|593|190
593|Jellicent|Water · Ghost||60
594|Alomomola|Water||75
595|Joltik|Bug · Electric|596|190
596|Galvantula|Bug · Electric||75
597|Ferroseed|Grass · Steel|598|255
598|Ferrothorn|Grass · Steel||90
599|Klink|Steel|600|130
600|Klang|Steel|601|60
601|Klinklang|Steel||30
602|Tynamo|Electric|603|190
603|Eelektrik|Electric|604|60
604|Eelektross|Electric||30
605|Elgyem|Psychic|606|255
606|Beheeyem|Psychic||90
607|Litwick|Ghost · Fire|608|190
608|Lampent|Ghost · Fire|609|90
609|Chandelure|Ghost · Fire||45
610|Axew|Dragon|611|75
611|Fraxure|Dragon|612|60
612|Haxorus|Dragon||45
613|Cubchoo|Ice|614|120
614|Beartic|Ice||60
615|Cryogonal|Ice||25
616|Shelmet|Bug|617|200
617|Accelgor|Bug||75
618|Stunfisk|Ground · Electric||75
619|Mienfoo|Fighting|620|180
620|Mienshao|Fighting||45
621|Druddigon|Dragon||45
622|Golett|Ground · Ghost|623|190
623|Golurk|Ground · Ghost||90
624|Pawniard|Dark · Steel|625|120
625|Bisharp|Dark · Steel|983|45
626|Bouffalant|Normal||45
627|Rufflet|Normal · Flying|628|190
628|Braviary|Normal · Flying||60
629|Vullaby|Dark · Flying|630|190
630|Mandibuzz|Dark · Flying||60
631|Heatmor|Fire||90
632|Durant|Bug · Steel||90
633|Deino|Dark · Dragon|634|45
634|Zweilous|Dark · Dragon|635|45
635|Hydreigon|Dark · Dragon||45
636|Larvesta|Bug · Fire|637|45
637|Volcarona|Bug · Fire||15
638|Cobalion|Steel · Fighting||3
639|Terrakion|Rock · Fighting||3
640|Virizion|Grass · Fighting||3
641|Tornadus|Flying||3
642|Thundurus|Electric · Flying||3
643|Reshiram|Dragon · Fire||3
644|Zekrom|Dragon · Electric||3
645|Landorus|Ground · Flying||3
646|Kyurem|Dragon · Ice||3
647|Keldeo|Water · Fighting||3
648|Meloetta|Normal · Psychic||3
649|Genesect|Bug · Steel||3
650|Chespin|Grass|651|45
651|Quilladin|Grass|652|45
652|Chesnaught|Grass · Fighting||45
653|Fennekin|Fire|654|45
654|Braixen|Fire|655|45
655|Delphox|Fire · Psychic||45
656|Froakie|Water|657|45
657|Frogadier|Water|658|45
658|Greninja|Water · Dark||45
659|Bunnelby|Normal|660|255
660|Diggersby|Normal · Ground||127
661|Fletchling|Normal · Flying|662|255
662|Fletchinder|Fire · Flying|663|120
663|Talonflame|Fire · Flying||45
664|Scatterbug|Bug|665|255
665|Spewpa|Bug|666|120
666|Vivillon|Bug · Flying||45
667|Litleo|Fire · Normal|668|220
668|Pyroar|Fire · Normal||65
669|Flabébé|Fairy|670|225
670|Floette|Fairy|671|120
671|Florges|Fairy||45
672|Skiddo|Grass|673|200
673|Gogoat|Grass||45
674|Pancham|Fighting|675|220
675|Pangoro|Fighting · Dark||65
676|Furfrou|Normal||160
677|Espurr|Psychic|678|190
678|Meowstic|Psychic||75
679|Honedge|Steel · Ghost|680|180
680|Doublade|Steel · Ghost|681|90
681|Aegislash|Steel · Ghost||45
682|Spritzee|Fairy|683|200
683|Aromatisse|Fairy||140
684|Swirlix|Fairy|685|200
685|Slurpuff|Fairy||140
686|Inkay|Dark · Psychic|687|190
687|Malamar|Dark · Psychic||80
688|Binacle|Rock · Water|689|120
689|Barbaracle|Rock · Water||45
690|Skrelp|Poison · Water|691|225
691|Dragalge|Poison · Dragon||55
692|Clauncher|Water|693|225
693|Clawitzer|Water||55
694|Helioptile|Electric · Normal|695|190
695|Heliolisk|Electric · Normal||75
696|Tyrunt|Rock · Dragon|697|45
697|Tyrantrum|Rock · Dragon||45
698|Amaura|Rock · Ice|699|45
699|Aurorus|Rock · Ice||45
700|Sylveon|Fairy||45
701|Hawlucha|Fighting · Flying||100
702|Dedenne|Electric · Fairy||180
703|Carbink|Rock · Fairy||60
704|Goomy|Dragon|705|45
705|Sliggoo|Dragon|706|45
706|Goodra|Dragon||45
707|Klefki|Steel · Fairy||75
708|Phantump|Ghost · Grass|709|120
709|Trevenant|Ghost · Grass||60
710|Pumpkaboo|Ghost · Grass|711|120
711|Gourgeist|Ghost · Grass||60
712|Bergmite|Ice|713|190
713|Avalugg|Ice||55
714|Noibat|Flying · Dragon|715|190
715|Noivern|Flying · Dragon||45
716|Xerneas|Fairy||45
717|Yveltal|Dark · Flying||45
718|Zygarde|Dragon · Ground||3
719|Diancie|Rock · Fairy||3
720|Hoopa|Psychic · Ghost||3
721|Volcanion|Fire · Water||3
722|Rowlet|Grass · Flying|723|45
723|Dartrix|Grass · Flying|724|45
724|Decidueye|Grass · Ghost||45
725|Litten|Fire|726|45
726|Torracat|Fire|727|45
727|Incineroar|Fire · Dark||45
728|Popplio|Water|729|45
729|Brionne|Water|730|45
730|Primarina|Water · Fairy||45
731|Pikipek|Normal · Flying|732|255
732|Trumbeak|Normal · Flying|733|120
733|Toucannon|Normal · Flying||45
734|Yungoos|Normal|735|255
735|Gumshoos|Normal||127
736|Grubbin|Bug|737|255
737|Charjabug|Bug · Electric|738|120
738|Vikavolt|Bug · Electric||45
739|Crabrawler|Fighting|740|225
740|Crabominable|Fighting · Ice||60
741|Oricorio|Fire · Flying||45
742|Cutiefly|Bug · Fairy|743|190
743|Ribombee|Bug · Fairy||75
744|Rockruff|Rock|745|190
745|Lycanroc|Rock||90
746|Wishiwashi|Water||60
747|Mareanie|Poison · Water|748|190
748|Toxapex|Poison · Water||75
749|Mudbray|Ground|750|190
750|Mudsdale|Ground||60
751|Dewpider|Water · Bug|752|200
752|Araquanid|Water · Bug||100
753|Fomantis|Grass|754|190
754|Lurantis|Grass||75
755|Morelull|Grass · Fairy|756|190
756|Shiinotic|Grass · Fairy||75
757|Salandit|Poison · Fire|758|120
758|Salazzle|Poison · Fire||45
759|Stufful|Normal · Fighting|760|140
760|Bewear|Normal · Fighting||70
761|Bounsweet|Grass|762|235
762|Steenee|Grass|763|120
763|Tsareena|Grass||45
764|Comfey|Fairy||60
765|Oranguru|Normal · Psychic||45
766|Passimian|Fighting||45
767|Wimpod|Bug · Water|768|90
768|Golisopod|Bug · Water||45
769|Sandygast|Ghost · Ground|770|140
770|Palossand|Ghost · Ground||60
771|Pyukumuku|Water||60
772|Type: Null|Normal|773|3
773|Silvally|Normal||3
774|Minior|Rock · Flying||30
775|Komala|Normal||45
776|Turtonator|Fire · Dragon||70
777|Togedemaru|Electric · Steel||180
778|Mimikyu|Ghost · Fairy||45
779|Bruxish|Water · Psychic||80
780|Drampa|Normal · Dragon||70
781|Dhelmise|Ghost · Grass||25
782|Jangmo-o|Dragon|783|45
783|Hakamo-o|Dragon · Fighting|784|45
784|Kommo-o|Dragon · Fighting||45
785|Tapu Koko|Electric · Fairy||3
786|Tapu Lele|Psychic · Fairy||3
787|Tapu Bulu|Grass · Fairy||3
788|Tapu Fini|Water · Fairy||3
789|Cosmog|Psychic|790|45
790|Cosmoem|Psychic|791|45
791|Solgaleo|Psychic · Steel||45
792|Lunala|Psychic · Ghost||45
793|Nihilego|Rock · Poison||45
794|Buzzwole|Bug · Fighting||45
795|Pheromosa|Bug · Fighting||45
796|Xurkitree|Electric||45
797|Celesteela|Steel · Flying||45
798|Kartana|Grass · Steel||45
799|Guzzlord|Dark · Dragon||45
800|Necrozma|Psychic||255
801|Magearna|Steel · Fairy||3
802|Marshadow|Fighting · Ghost||3
803|Poipole|Poison|804|45
804|Naganadel|Poison · Dragon||45
805|Stakataka|Rock · Steel||30
806|Blacephalon|Fire · Ghost||30
807|Zeraora|Electric||3
808|Meltan|Steel|809|3
809|Melmetal|Steel||3
810|Grookey|Grass|811|45
811|Thwackey|Grass|812|45
812|Rillaboom|Grass||45
813|Scorbunny|Fire|814|45
814|Raboot|Fire|815|45
815|Cinderace|Fire||45
816|Sobble|Water|817|45
817|Drizzile|Water|818|45
818|Inteleon|Water||45
819|Skwovet|Normal|820|255
820|Greedent|Normal||90
821|Rookidee|Flying|822|255
822|Corvisquire|Flying|823|120
823|Corviknight|Flying · Steel||45
824|Blipbug|Bug|825|255
825|Dottler|Bug · Psychic|826|120
826|Orbeetle|Bug · Psychic||45
827|Nickit|Dark|828|255
828|Thievul|Dark||127
829|Gossifleur|Grass|830|190
830|Eldegoss|Grass||75
831|Wooloo|Normal|832|255
832|Dubwool|Normal||127
833|Chewtle|Water|834|255
834|Drednaw|Water · Rock||75
835|Yamper|Electric|836|255
836|Boltund|Electric||45
837|Rolycoly|Rock|838|255
838|Carkol|Rock · Fire|839|120
839|Coalossal|Rock · Fire||45
840|Applin|Grass · Dragon|841|255
841|Flapple|Grass · Dragon||45
842|Appletun|Grass · Dragon||45
843|Silicobra|Ground|844|255
844|Sandaconda|Ground||120
845|Cramorant|Flying · Water||45
846|Arrokuda|Water|847|255
847|Barraskewda|Water||60
848|Toxel|Electric · Poison|849|75
849|Toxtricity|Electric · Poison||45
850|Sizzlipede|Fire · Bug|851|190
851|Centiskorch|Fire · Bug||75
852|Clobbopus|Fighting|853|180
853|Grapploct|Fighting||45
854|Sinistea|Ghost|855|120
855|Polteageist|Ghost||60
856|Hatenna|Psychic|857|235
857|Hattrem|Psychic|858|120
858|Hatterene|Psychic · Fairy||45
859|Impidimp|Dark · Fairy|860|255
860|Morgrem|Dark · Fairy|861|120
861|Grimmsnarl|Dark · Fairy||45
862|Obstagoon|Dark · Normal||45
863|Perrserker|Steel||90
864|Cursola|Ghost||30
865|Sirfetch’d|Fighting||45
866|Mr. Rime|Ice · Psychic||45
867|Runerigus|Ground · Ghost||90
868|Milcery|Fairy|869|200
869|Alcremie|Fairy||100
870|Falinks|Fighting||45
871|Pincurchin|Electric||75
872|Snom|Ice · Bug|873|190
873|Frosmoth|Ice · Bug||75
874|Stonjourner|Rock||60
875|Eiscue|Ice||60
876|Indeedee|Psychic · Normal||30
877|Morpeko|Electric · Dark||180
878|Cufant|Steel|879|190
879|Copperajah|Steel||90
880|Dracozolt|Electric · Dragon||45
881|Arctozolt|Electric · Ice||45
882|Dracovish|Water · Dragon||45
883|Arctovish|Water · Ice||45
884|Duraludon|Steel · Dragon|1018|45
885|Dreepy|Dragon · Ghost|886|45
886|Drakloak|Dragon · Ghost|887|45
887|Dragapult|Dragon · Ghost||45
888|Zacian|Fairy||10
889|Zamazenta|Fighting||10
890|Eternatus|Poison · Dragon||255
891|Kubfu|Fighting|892|3
892|Urshifu|Fighting · Dark||3
893|Zarude|Dark · Grass||3
894|Regieleki|Electric||3
895|Regidrago|Dragon||3
896|Glastrier|Ice||3
897|Spectrier|Ghost||3
898|Calyrex|Psychic · Grass||3
899|Wyrdeer|Normal · Psychic||135
900|Kleavor|Bug · Rock||115
901|Ursaluna|Ground · Normal||75
902|Basculegion|Water · Ghost||135
903|Sneasler|Fighting · Poison||135
904|Overqwil|Dark · Poison||135
905|Enamorus|Fairy · Flying||3
906|Sprigatito|Grass|907|45
907|Floragato|Grass|908|45
908|Meowscarada|Grass · Dark||45
909|Fuecoco|Fire|910|45
910|Crocalor|Fire|911|45
911|Skeledirge|Fire · Ghost||45
912|Quaxly|Water|913|45
913|Quaxwell|Water|914|45
914|Quaquaval|Water · Fighting||45
915|Lechonk|Normal|916|255
916|Oinkologne|Normal||100
917|Tarountula|Bug|918|255
918|Spidops|Bug||120
919|Nymble|Bug|920|190
920|Lokix|Bug · Dark||30
921|Pawmi|Electric|922|190
922|Pawmo|Electric · Fighting|923|80
923|Pawmot|Electric · Fighting||45
924|Tandemaus|Normal|925|150
925|Maushold|Normal||75
926|Fidough|Fairy|927|190
927|Dachsbun|Fairy||90
928|Smoliv|Grass · Normal|929|255
929|Dolliv|Grass · Normal|930|120
930|Arboliva|Grass · Normal||45
931|Squawkabilly|Normal · Flying||190
932|Nacli|Rock|933|255
933|Naclstack|Rock|934|120
934|Garganacl|Rock||45
935|Charcadet|Fire|936|90
936|Armarouge|Fire · Psychic||25
937|Ceruledge|Fire · Ghost||25
938|Tadbulb|Electric|939|190
939|Bellibolt|Electric||50
940|Wattrel|Electric · Flying|941|180
941|Kilowattrel|Electric · Flying||90
942|Maschiff|Dark|943|150
943|Mabosstiff|Dark||75
944|Shroodle|Poison · Normal|945|190
945|Grafaiai|Poison · Normal||90
946|Bramblin|Grass · Ghost|947|190
947|Brambleghast|Grass · Ghost||45
948|Toedscool|Ground · Grass|949|190
949|Toedscruel|Ground · Grass||90
950|Klawf|Rock||120
951|Capsakid|Grass|952|190
952|Scovillain|Grass · Fire||75
953|Rellor|Bug|954|190
954|Rabsca|Bug · Psychic||45
955|Flittle|Psychic|956|120
956|Espathra|Psychic||60
957|Tinkatink|Fairy · Steel|958|190
958|Tinkatuff|Fairy · Steel|959|90
959|Tinkaton|Fairy · Steel||45
960|Wiglett|Water|961|255
961|Wugtrio|Water||50
962|Bombirdier|Flying · Dark||25
963|Finizen|Water|964|200
964|Palafin|Water||45
965|Varoom|Steel · Poison|966|190
966|Revavroom|Steel · Poison||75
967|Cyclizar|Dragon · Normal||190
968|Orthworm|Steel||25
969|Glimmet|Rock · Poison|970|70
970|Glimmora|Rock · Poison||25
971|Greavard|Ghost|972|120
972|Houndstone|Ghost||60
973|Flamigo|Flying · Fighting||100
974|Cetoddle|Ice|975|150
975|Cetitan|Ice||50
976|Veluza|Water · Psychic||100
977|Dondozo|Water||25
978|Tatsugiri|Dragon · Water||100
979|Annihilape|Fighting · Ghost||45
980|Clodsire|Poison · Ground||90
981|Farigiraf|Normal · Psychic||45
982|Dudunsparce|Normal||45
983|Kingambit|Dark · Steel||25
984|Great Tusk|Ground · Fighting||30
985|Scream Tail|Fairy · Psychic||50
986|Brute Bonnet|Grass · Dark||50
987|Flutter Mane|Ghost · Fairy||30
988|Slither Wing|Bug · Fighting||30
989|Sandy Shocks|Electric · Ground||30
990|Iron Treads|Ground · Steel||30
991|Iron Bundle|Ice · Water||50
992|Iron Hands|Fighting · Electric||50
993|Iron Jugulis|Dark · Flying||30
994|Iron Moth|Fire · Poison||30
995|Iron Thorns|Rock · Electric||30
996|Frigibax|Dragon · Ice|997|45
997|Arctibax|Dragon · Ice|998|25
998|Baxcalibur|Dragon · Ice||10
999|Gimmighoul|Ghost|1000|45
1000|Gholdengo|Steel · Ghost||45
1001|Wo-Chien|Dark · Grass||6
1002|Chien-Pao|Dark · Ice||6
1003|Ting-Lu|Dark · Ground||6
1004|Chi-Yu|Dark · Fire||6
1005|Roaring Moon|Dragon · Dark||10
1006|Iron Valiant|Fairy · Fighting||10
1007|Koraidon|Fighting · Dragon||3
1008|Miraidon|Electric · Dragon||3
1009|Walking Wake|Water · Dragon||5
1010|Iron Leaves|Grass · Psychic||5
1011|Dipplin|Grass · Dragon|1019|45
1012|Poltchageist|Grass · Ghost|1013|120
1013|Sinistcha|Grass · Ghost||60
1014|Okidogi|Poison · Fighting||3
1015|Munkidori|Poison · Psychic||3
1016|Fezandipiti|Poison · Fairy||3
1017|Ogerpon|Grass||5
1018|Archaludon|Steel · Dragon||10
1019|Hydrapple|Grass · Dragon||10
1020|Gouging Fire|Fire · Dragon||10
1021|Raging Bolt|Electric · Dragon||10
1022|Iron Boulder|Rock · Psychic||10
1023|Iron Crown|Steel · Psychic||10
1024|Terapagos|Normal||255
1025|Pecharunt|Poison · Ghost||3
"""
