// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 chuahchengxi

// Generated by Tools/gen-species-catalog.py from the PokeAPI CSV dumps.
// The full National Dex, one line per species: id|Name|Types|nextEvolutionID.
// Parsed at first use rather than written as struct literals, which the
// Swift type checker takes minutes to chew through at this size.

let speciesCatalogData = """
1|Bulbasaur|Grass · Poison|2
2|Ivysaur|Grass · Poison|3
3|Venusaur|Grass · Poison|
4|Charmander|Fire|5
5|Charmeleon|Fire|6
6|Charizard|Fire · Flying|
7|Squirtle|Water|8
8|Wartortle|Water|9
9|Blastoise|Water|
10|Caterpie|Bug|11
11|Metapod|Bug|12
12|Butterfree|Bug · Flying|
13|Weedle|Bug · Poison|14
14|Kakuna|Bug · Poison|15
15|Beedrill|Bug · Poison|
16|Pidgey|Normal · Flying|17
17|Pidgeotto|Normal · Flying|18
18|Pidgeot|Normal · Flying|
19|Rattata|Normal|20
20|Raticate|Normal|
21|Spearow|Normal · Flying|22
22|Fearow|Normal · Flying|
23|Ekans|Poison|24
24|Arbok|Poison|
25|Pikachu|Electric|26
26|Raichu|Electric|
27|Sandshrew|Ground|28
28|Sandslash|Ground|
29|Nidoran♀|Poison|30
30|Nidorina|Poison|31
31|Nidoqueen|Poison · Ground|
32|Nidoran♂|Poison|33
33|Nidorino|Poison|34
34|Nidoking|Poison · Ground|
35|Clefairy|Fairy|36
36|Clefable|Fairy|
37|Vulpix|Fire|38
38|Ninetales|Fire|
39|Jigglypuff|Normal · Fairy|40
40|Wigglytuff|Normal · Fairy|
41|Zubat|Poison · Flying|42
42|Golbat|Poison · Flying|169
43|Oddish|Grass · Poison|44
44|Gloom|Grass · Poison|45
45|Vileplume|Grass · Poison|
46|Paras|Bug · Grass|47
47|Parasect|Bug · Grass|
48|Venonat|Bug · Poison|49
49|Venomoth|Bug · Poison|
50|Diglett|Ground|51
51|Dugtrio|Ground|
52|Meowth|Normal|53
53|Persian|Normal|
54|Psyduck|Water|55
55|Golduck|Water|
56|Mankey|Fighting|57
57|Primeape|Fighting|979
58|Growlithe|Fire|59
59|Arcanine|Fire|
60|Poliwag|Water|61
61|Poliwhirl|Water|62
62|Poliwrath|Water · Fighting|
63|Abra|Psychic|64
64|Kadabra|Psychic|65
65|Alakazam|Psychic|
66|Machop|Fighting|67
67|Machoke|Fighting|68
68|Machamp|Fighting|
69|Bellsprout|Grass · Poison|70
70|Weepinbell|Grass · Poison|71
71|Victreebel|Grass · Poison|
72|Tentacool|Water · Poison|73
73|Tentacruel|Water · Poison|
74|Geodude|Rock · Ground|75
75|Graveler|Rock · Ground|76
76|Golem|Rock · Ground|
77|Ponyta|Fire|78
78|Rapidash|Fire|
79|Slowpoke|Water · Psychic|80
80|Slowbro|Water · Psychic|
81|Magnemite|Electric · Steel|82
82|Magneton|Electric · Steel|462
83|Farfetch’d|Normal · Flying|865
84|Doduo|Normal · Flying|85
85|Dodrio|Normal · Flying|
86|Seel|Water|87
87|Dewgong|Water · Ice|
88|Grimer|Poison|89
89|Muk|Poison|
90|Shellder|Water|91
91|Cloyster|Water · Ice|
92|Gastly|Ghost · Poison|93
93|Haunter|Ghost · Poison|94
94|Gengar|Ghost · Poison|
95|Onix|Rock · Ground|208
96|Drowzee|Psychic|97
97|Hypno|Psychic|
98|Krabby|Water|99
99|Kingler|Water|
100|Voltorb|Electric|101
101|Electrode|Electric|
102|Exeggcute|Grass · Psychic|103
103|Exeggutor|Grass · Psychic|
104|Cubone|Ground|105
105|Marowak|Ground|
106|Hitmonlee|Fighting|
107|Hitmonchan|Fighting|
108|Lickitung|Normal|463
109|Koffing|Poison|110
110|Weezing|Poison|
111|Rhyhorn|Ground · Rock|112
112|Rhydon|Ground · Rock|464
113|Chansey|Normal|242
114|Tangela|Grass|465
115|Kangaskhan|Normal|
116|Horsea|Water|117
117|Seadra|Water|230
118|Goldeen|Water|119
119|Seaking|Water|
120|Staryu|Water|121
121|Starmie|Water · Psychic|
122|Mr. Mime|Psychic · Fairy|866
123|Scyther|Bug · Flying|212
124|Jynx|Ice · Psychic|
125|Electabuzz|Electric|466
126|Magmar|Fire|467
127|Pinsir|Bug|
128|Tauros|Normal|
129|Magikarp|Water|130
130|Gyarados|Water · Flying|
131|Lapras|Water · Ice|
132|Ditto|Normal|
133|Eevee|Normal|134
134|Vaporeon|Water|
135|Jolteon|Electric|
136|Flareon|Fire|
137|Porygon|Normal|233
138|Omanyte|Rock · Water|139
139|Omastar|Rock · Water|
140|Kabuto|Rock · Water|141
141|Kabutops|Rock · Water|
142|Aerodactyl|Rock · Flying|
143|Snorlax|Normal|
144|Articuno|Ice · Flying|
145|Zapdos|Electric · Flying|
146|Moltres|Fire · Flying|
147|Dratini|Dragon|148
148|Dragonair|Dragon|149
149|Dragonite|Dragon · Flying|
150|Mewtwo|Psychic|
151|Mew|Psychic|
152|Chikorita|Grass|153
153|Bayleef|Grass|154
154|Meganium|Grass|
155|Cyndaquil|Fire|156
156|Quilava|Fire|157
157|Typhlosion|Fire|
158|Totodile|Water|159
159|Croconaw|Water|160
160|Feraligatr|Water|
161|Sentret|Normal|162
162|Furret|Normal|
163|Hoothoot|Normal · Flying|164
164|Noctowl|Normal · Flying|
165|Ledyba|Bug · Flying|166
166|Ledian|Bug · Flying|
167|Spinarak|Bug · Poison|168
168|Ariados|Bug · Poison|
169|Crobat|Poison · Flying|
170|Chinchou|Water · Electric|171
171|Lanturn|Water · Electric|
172|Pichu|Electric|25
173|Cleffa|Fairy|35
174|Igglybuff|Normal · Fairy|39
175|Togepi|Fairy|176
176|Togetic|Fairy · Flying|468
177|Natu|Psychic · Flying|178
178|Xatu|Psychic · Flying|
179|Mareep|Electric|180
180|Flaaffy|Electric|181
181|Ampharos|Electric|
182|Bellossom|Grass|
183|Marill|Water · Fairy|184
184|Azumarill|Water · Fairy|
185|Sudowoodo|Rock|
186|Politoed|Water|
187|Hoppip|Grass · Flying|188
188|Skiploom|Grass · Flying|189
189|Jumpluff|Grass · Flying|
190|Aipom|Normal|424
191|Sunkern|Grass|192
192|Sunflora|Grass|
193|Yanma|Bug · Flying|469
194|Wooper|Water · Ground|195
195|Quagsire|Water · Ground|
196|Espeon|Psychic|
197|Umbreon|Dark|
198|Murkrow|Dark · Flying|430
199|Slowking|Water · Psychic|
200|Misdreavus|Ghost|429
201|Unown|Psychic|
202|Wobbuffet|Psychic|
203|Girafarig|Normal · Psychic|981
204|Pineco|Bug|205
205|Forretress|Bug · Steel|
206|Dunsparce|Normal|982
207|Gligar|Ground · Flying|472
208|Steelix|Steel · Ground|
209|Snubbull|Fairy|210
210|Granbull|Fairy|
211|Qwilfish|Water · Poison|904
212|Scizor|Bug · Steel|
213|Shuckle|Bug · Rock|
214|Heracross|Bug · Fighting|
215|Sneasel|Dark · Ice|461
216|Teddiursa|Normal|217
217|Ursaring|Normal|901
218|Slugma|Fire|219
219|Magcargo|Fire · Rock|
220|Swinub|Ice · Ground|221
221|Piloswine|Ice · Ground|473
222|Corsola|Water · Rock|864
223|Remoraid|Water|224
224|Octillery|Water|
225|Delibird|Ice · Flying|
226|Mantine|Water · Flying|
227|Skarmory|Steel · Flying|
228|Houndour|Dark · Fire|229
229|Houndoom|Dark · Fire|
230|Kingdra|Water · Dragon|
231|Phanpy|Ground|232
232|Donphan|Ground|
233|Porygon2|Normal|474
234|Stantler|Normal|899
235|Smeargle|Normal|
236|Tyrogue|Fighting|106
237|Hitmontop|Fighting|
238|Smoochum|Ice · Psychic|124
239|Elekid|Electric|125
240|Magby|Fire|126
241|Miltank|Normal|
242|Blissey|Normal|
243|Raikou|Electric|
244|Entei|Fire|
245|Suicune|Water|
246|Larvitar|Rock · Ground|247
247|Pupitar|Rock · Ground|248
248|Tyranitar|Rock · Dark|
249|Lugia|Psychic · Flying|
250|Ho-Oh|Fire · Flying|
251|Celebi|Psychic · Grass|
252|Treecko|Grass|253
253|Grovyle|Grass|254
254|Sceptile|Grass|
255|Torchic|Fire|256
256|Combusken|Fire · Fighting|257
257|Blaziken|Fire · Fighting|
258|Mudkip|Water|259
259|Marshtomp|Water · Ground|260
260|Swampert|Water · Ground|
261|Poochyena|Dark|262
262|Mightyena|Dark|
263|Zigzagoon|Normal|264
264|Linoone|Normal|862
265|Wurmple|Bug|266
266|Silcoon|Bug|267
267|Beautifly|Bug · Flying|
268|Cascoon|Bug|269
269|Dustox|Bug · Poison|
270|Lotad|Water · Grass|271
271|Lombre|Water · Grass|272
272|Ludicolo|Water · Grass|
273|Seedot|Grass|274
274|Nuzleaf|Grass · Dark|275
275|Shiftry|Grass · Dark|
276|Taillow|Normal · Flying|277
277|Swellow|Normal · Flying|
278|Wingull|Water · Flying|279
279|Pelipper|Water · Flying|
280|Ralts|Psychic · Fairy|281
281|Kirlia|Psychic · Fairy|282
282|Gardevoir|Psychic · Fairy|
283|Surskit|Bug · Water|284
284|Masquerain|Bug · Flying|
285|Shroomish|Grass|286
286|Breloom|Grass · Fighting|
287|Slakoth|Normal|288
288|Vigoroth|Normal|289
289|Slaking|Normal|
290|Nincada|Bug · Ground|291
291|Ninjask|Bug · Flying|
292|Shedinja|Bug · Ghost|
293|Whismur|Normal|294
294|Loudred|Normal|295
295|Exploud|Normal|
296|Makuhita|Fighting|297
297|Hariyama|Fighting|
298|Azurill|Normal · Fairy|183
299|Nosepass|Rock|476
300|Skitty|Normal|301
301|Delcatty|Normal|
302|Sableye|Dark · Ghost|
303|Mawile|Steel · Fairy|
304|Aron|Steel · Rock|305
305|Lairon|Steel · Rock|306
306|Aggron|Steel · Rock|
307|Meditite|Fighting · Psychic|308
308|Medicham|Fighting · Psychic|
309|Electrike|Electric|310
310|Manectric|Electric|
311|Plusle|Electric|
312|Minun|Electric|
313|Volbeat|Bug|
314|Illumise|Bug|
315|Roselia|Grass · Poison|407
316|Gulpin|Poison|317
317|Swalot|Poison|
318|Carvanha|Water · Dark|319
319|Sharpedo|Water · Dark|
320|Wailmer|Water|321
321|Wailord|Water|
322|Numel|Fire · Ground|323
323|Camerupt|Fire · Ground|
324|Torkoal|Fire|
325|Spoink|Psychic|326
326|Grumpig|Psychic|
327|Spinda|Normal|
328|Trapinch|Ground|329
329|Vibrava|Ground · Dragon|330
330|Flygon|Ground · Dragon|
331|Cacnea|Grass|332
332|Cacturne|Grass · Dark|
333|Swablu|Normal · Flying|334
334|Altaria|Dragon · Flying|
335|Zangoose|Normal|
336|Seviper|Poison|
337|Lunatone|Rock · Psychic|
338|Solrock|Rock · Psychic|
339|Barboach|Water · Ground|340
340|Whiscash|Water · Ground|
341|Corphish|Water|342
342|Crawdaunt|Water · Dark|
343|Baltoy|Ground · Psychic|344
344|Claydol|Ground · Psychic|
345|Lileep|Rock · Grass|346
346|Cradily|Rock · Grass|
347|Anorith|Rock · Bug|348
348|Armaldo|Rock · Bug|
349|Feebas|Water|350
350|Milotic|Water|
351|Castform|Normal|
352|Kecleon|Normal|
353|Shuppet|Ghost|354
354|Banette|Ghost|
355|Duskull|Ghost|356
356|Dusclops|Ghost|477
357|Tropius|Grass · Flying|
358|Chimecho|Psychic|
359|Absol|Dark|
360|Wynaut|Psychic|202
361|Snorunt|Ice|362
362|Glalie|Ice|
363|Spheal|Ice · Water|364
364|Sealeo|Ice · Water|365
365|Walrein|Ice · Water|
366|Clamperl|Water|367
367|Huntail|Water|
368|Gorebyss|Water|
369|Relicanth|Water · Rock|
370|Luvdisc|Water|
371|Bagon|Dragon|372
372|Shelgon|Dragon|373
373|Salamence|Dragon · Flying|
374|Beldum|Steel · Psychic|375
375|Metang|Steel · Psychic|376
376|Metagross|Steel · Psychic|
377|Regirock|Rock|
378|Regice|Ice|
379|Registeel|Steel|
380|Latias|Dragon · Psychic|
381|Latios|Dragon · Psychic|
382|Kyogre|Water|
383|Groudon|Ground|
384|Rayquaza|Dragon · Flying|
385|Jirachi|Steel · Psychic|
386|Deoxys|Psychic|
387|Turtwig|Grass|388
388|Grotle|Grass|389
389|Torterra|Grass · Ground|
390|Chimchar|Fire|391
391|Monferno|Fire · Fighting|392
392|Infernape|Fire · Fighting|
393|Piplup|Water|394
394|Prinplup|Water|395
395|Empoleon|Water · Steel|
396|Starly|Normal · Flying|397
397|Staravia|Normal · Flying|398
398|Staraptor|Normal · Flying|
399|Bidoof|Normal|400
400|Bibarel|Normal · Water|
401|Kricketot|Bug|402
402|Kricketune|Bug|
403|Shinx|Electric|404
404|Luxio|Electric|405
405|Luxray|Electric|
406|Budew|Grass · Poison|315
407|Roserade|Grass · Poison|
408|Cranidos|Rock|409
409|Rampardos|Rock|
410|Shieldon|Rock · Steel|411
411|Bastiodon|Rock · Steel|
412|Burmy|Bug|413
413|Wormadam|Bug · Grass|
414|Mothim|Bug · Flying|
415|Combee|Bug · Flying|416
416|Vespiquen|Bug · Flying|
417|Pachirisu|Electric|
418|Buizel|Water|419
419|Floatzel|Water|
420|Cherubi|Grass|421
421|Cherrim|Grass|
422|Shellos|Water|423
423|Gastrodon|Water · Ground|
424|Ambipom|Normal|
425|Drifloon|Ghost · Flying|426
426|Drifblim|Ghost · Flying|
427|Buneary|Normal|428
428|Lopunny|Normal|
429|Mismagius|Ghost|
430|Honchkrow|Dark · Flying|
431|Glameow|Normal|432
432|Purugly|Normal|
433|Chingling|Psychic|358
434|Stunky|Poison · Dark|435
435|Skuntank|Poison · Dark|
436|Bronzor|Steel · Psychic|437
437|Bronzong|Steel · Psychic|
438|Bonsly|Rock|185
439|Mime Jr.|Psychic · Fairy|122
440|Happiny|Normal|113
441|Chatot|Normal · Flying|
442|Spiritomb|Ghost · Dark|
443|Gible|Dragon · Ground|444
444|Gabite|Dragon · Ground|445
445|Garchomp|Dragon · Ground|
446|Munchlax|Normal|143
447|Riolu|Fighting|448
448|Lucario|Fighting · Steel|
449|Hippopotas|Ground|450
450|Hippowdon|Ground|
451|Skorupi|Poison · Bug|452
452|Drapion|Poison · Dark|
453|Croagunk|Poison · Fighting|454
454|Toxicroak|Poison · Fighting|
455|Carnivine|Grass|
456|Finneon|Water|457
457|Lumineon|Water|
458|Mantyke|Water · Flying|226
459|Snover|Grass · Ice|460
460|Abomasnow|Grass · Ice|
461|Weavile|Dark · Ice|
462|Magnezone|Electric · Steel|
463|Lickilicky|Normal|
464|Rhyperior|Ground · Rock|
465|Tangrowth|Grass|
466|Electivire|Electric|
467|Magmortar|Fire|
468|Togekiss|Fairy · Flying|
469|Yanmega|Bug · Flying|
470|Leafeon|Grass|
471|Glaceon|Ice|
472|Gliscor|Ground · Flying|
473|Mamoswine|Ice · Ground|
474|Porygon-Z|Normal|
475|Gallade|Psychic · Fighting|
476|Probopass|Rock · Steel|
477|Dusknoir|Ghost|
478|Froslass|Ice · Ghost|
479|Rotom|Electric · Ghost|
480|Uxie|Psychic|
481|Mesprit|Psychic|
482|Azelf|Psychic|
483|Dialga|Steel · Dragon|
484|Palkia|Water · Dragon|
485|Heatran|Fire · Steel|
486|Regigigas|Normal|
487|Giratina|Ghost · Dragon|
488|Cresselia|Psychic|
489|Phione|Water|
490|Manaphy|Water|
491|Darkrai|Dark|
492|Shaymin|Grass|
493|Arceus|Normal|
494|Victini|Psychic · Fire|
495|Snivy|Grass|496
496|Servine|Grass|497
497|Serperior|Grass|
498|Tepig|Fire|499
499|Pignite|Fire · Fighting|500
500|Emboar|Fire · Fighting|
501|Oshawott|Water|502
502|Dewott|Water|503
503|Samurott|Water|
504|Patrat|Normal|505
505|Watchog|Normal|
506|Lillipup|Normal|507
507|Herdier|Normal|508
508|Stoutland|Normal|
509|Purrloin|Dark|510
510|Liepard|Dark|
511|Pansage|Grass|512
512|Simisage|Grass|
513|Pansear|Fire|514
514|Simisear|Fire|
515|Panpour|Water|516
516|Simipour|Water|
517|Munna|Psychic|518
518|Musharna|Psychic|
519|Pidove|Normal · Flying|520
520|Tranquill|Normal · Flying|521
521|Unfezant|Normal · Flying|
522|Blitzle|Electric|523
523|Zebstrika|Electric|
524|Roggenrola|Rock|525
525|Boldore|Rock|526
526|Gigalith|Rock|
527|Woobat|Psychic · Flying|528
528|Swoobat|Psychic · Flying|
529|Drilbur|Ground|530
530|Excadrill|Ground · Steel|
531|Audino|Normal|
532|Timburr|Fighting|533
533|Gurdurr|Fighting|534
534|Conkeldurr|Fighting|
535|Tympole|Water|536
536|Palpitoad|Water · Ground|537
537|Seismitoad|Water · Ground|
538|Throh|Fighting|
539|Sawk|Fighting|
540|Sewaddle|Bug · Grass|541
541|Swadloon|Bug · Grass|542
542|Leavanny|Bug · Grass|
543|Venipede|Bug · Poison|544
544|Whirlipede|Bug · Poison|545
545|Scolipede|Bug · Poison|
546|Cottonee|Grass · Fairy|547
547|Whimsicott|Grass · Fairy|
548|Petilil|Grass|549
549|Lilligant|Grass|
550|Basculin|Water|902
551|Sandile|Ground · Dark|552
552|Krokorok|Ground · Dark|553
553|Krookodile|Ground · Dark|
554|Darumaka|Fire|555
555|Darmanitan|Fire|
556|Maractus|Grass|
557|Dwebble|Bug · Rock|558
558|Crustle|Bug · Rock|
559|Scraggy|Dark · Fighting|560
560|Scrafty|Dark · Fighting|
561|Sigilyph|Psychic · Flying|
562|Yamask|Ghost|563
563|Cofagrigus|Ghost|
564|Tirtouga|Water · Rock|565
565|Carracosta|Water · Rock|
566|Archen|Rock · Flying|567
567|Archeops|Rock · Flying|
568|Trubbish|Poison|569
569|Garbodor|Poison|
570|Zorua|Dark|571
571|Zoroark|Dark|
572|Minccino|Normal|573
573|Cinccino|Normal|
574|Gothita|Psychic|575
575|Gothorita|Psychic|576
576|Gothitelle|Psychic|
577|Solosis|Psychic|578
578|Duosion|Psychic|579
579|Reuniclus|Psychic|
580|Ducklett|Water · Flying|581
581|Swanna|Water · Flying|
582|Vanillite|Ice|583
583|Vanillish|Ice|584
584|Vanilluxe|Ice|
585|Deerling|Normal · Grass|586
586|Sawsbuck|Normal · Grass|
587|Emolga|Electric · Flying|
588|Karrablast|Bug|589
589|Escavalier|Bug · Steel|
590|Foongus|Grass · Poison|591
591|Amoonguss|Grass · Poison|
592|Frillish|Water · Ghost|593
593|Jellicent|Water · Ghost|
594|Alomomola|Water|
595|Joltik|Bug · Electric|596
596|Galvantula|Bug · Electric|
597|Ferroseed|Grass · Steel|598
598|Ferrothorn|Grass · Steel|
599|Klink|Steel|600
600|Klang|Steel|601
601|Klinklang|Steel|
602|Tynamo|Electric|603
603|Eelektrik|Electric|604
604|Eelektross|Electric|
605|Elgyem|Psychic|606
606|Beheeyem|Psychic|
607|Litwick|Ghost · Fire|608
608|Lampent|Ghost · Fire|609
609|Chandelure|Ghost · Fire|
610|Axew|Dragon|611
611|Fraxure|Dragon|612
612|Haxorus|Dragon|
613|Cubchoo|Ice|614
614|Beartic|Ice|
615|Cryogonal|Ice|
616|Shelmet|Bug|617
617|Accelgor|Bug|
618|Stunfisk|Ground · Electric|
619|Mienfoo|Fighting|620
620|Mienshao|Fighting|
621|Druddigon|Dragon|
622|Golett|Ground · Ghost|623
623|Golurk|Ground · Ghost|
624|Pawniard|Dark · Steel|625
625|Bisharp|Dark · Steel|983
626|Bouffalant|Normal|
627|Rufflet|Normal · Flying|628
628|Braviary|Normal · Flying|
629|Vullaby|Dark · Flying|630
630|Mandibuzz|Dark · Flying|
631|Heatmor|Fire|
632|Durant|Bug · Steel|
633|Deino|Dark · Dragon|634
634|Zweilous|Dark · Dragon|635
635|Hydreigon|Dark · Dragon|
636|Larvesta|Bug · Fire|637
637|Volcarona|Bug · Fire|
638|Cobalion|Steel · Fighting|
639|Terrakion|Rock · Fighting|
640|Virizion|Grass · Fighting|
641|Tornadus|Flying|
642|Thundurus|Electric · Flying|
643|Reshiram|Dragon · Fire|
644|Zekrom|Dragon · Electric|
645|Landorus|Ground · Flying|
646|Kyurem|Dragon · Ice|
647|Keldeo|Water · Fighting|
648|Meloetta|Normal · Psychic|
649|Genesect|Bug · Steel|
650|Chespin|Grass|651
651|Quilladin|Grass|652
652|Chesnaught|Grass · Fighting|
653|Fennekin|Fire|654
654|Braixen|Fire|655
655|Delphox|Fire · Psychic|
656|Froakie|Water|657
657|Frogadier|Water|658
658|Greninja|Water · Dark|
659|Bunnelby|Normal|660
660|Diggersby|Normal · Ground|
661|Fletchling|Normal · Flying|662
662|Fletchinder|Fire · Flying|663
663|Talonflame|Fire · Flying|
664|Scatterbug|Bug|665
665|Spewpa|Bug|666
666|Vivillon|Bug · Flying|
667|Litleo|Fire · Normal|668
668|Pyroar|Fire · Normal|
669|Flabébé|Fairy|670
670|Floette|Fairy|671
671|Florges|Fairy|
672|Skiddo|Grass|673
673|Gogoat|Grass|
674|Pancham|Fighting|675
675|Pangoro|Fighting · Dark|
676|Furfrou|Normal|
677|Espurr|Psychic|678
678|Meowstic|Psychic|
679|Honedge|Steel · Ghost|680
680|Doublade|Steel · Ghost|681
681|Aegislash|Steel · Ghost|
682|Spritzee|Fairy|683
683|Aromatisse|Fairy|
684|Swirlix|Fairy|685
685|Slurpuff|Fairy|
686|Inkay|Dark · Psychic|687
687|Malamar|Dark · Psychic|
688|Binacle|Rock · Water|689
689|Barbaracle|Rock · Water|
690|Skrelp|Poison · Water|691
691|Dragalge|Poison · Dragon|
692|Clauncher|Water|693
693|Clawitzer|Water|
694|Helioptile|Electric · Normal|695
695|Heliolisk|Electric · Normal|
696|Tyrunt|Rock · Dragon|697
697|Tyrantrum|Rock · Dragon|
698|Amaura|Rock · Ice|699
699|Aurorus|Rock · Ice|
700|Sylveon|Fairy|
701|Hawlucha|Fighting · Flying|
702|Dedenne|Electric · Fairy|
703|Carbink|Rock · Fairy|
704|Goomy|Dragon|705
705|Sliggoo|Dragon|706
706|Goodra|Dragon|
707|Klefki|Steel · Fairy|
708|Phantump|Ghost · Grass|709
709|Trevenant|Ghost · Grass|
710|Pumpkaboo|Ghost · Grass|711
711|Gourgeist|Ghost · Grass|
712|Bergmite|Ice|713
713|Avalugg|Ice|
714|Noibat|Flying · Dragon|715
715|Noivern|Flying · Dragon|
716|Xerneas|Fairy|
717|Yveltal|Dark · Flying|
718|Zygarde|Dragon · Ground|
719|Diancie|Rock · Fairy|
720|Hoopa|Psychic · Ghost|
721|Volcanion|Fire · Water|
722|Rowlet|Grass · Flying|723
723|Dartrix|Grass · Flying|724
724|Decidueye|Grass · Ghost|
725|Litten|Fire|726
726|Torracat|Fire|727
727|Incineroar|Fire · Dark|
728|Popplio|Water|729
729|Brionne|Water|730
730|Primarina|Water · Fairy|
731|Pikipek|Normal · Flying|732
732|Trumbeak|Normal · Flying|733
733|Toucannon|Normal · Flying|
734|Yungoos|Normal|735
735|Gumshoos|Normal|
736|Grubbin|Bug|737
737|Charjabug|Bug · Electric|738
738|Vikavolt|Bug · Electric|
739|Crabrawler|Fighting|740
740|Crabominable|Fighting · Ice|
741|Oricorio|Fire · Flying|
742|Cutiefly|Bug · Fairy|743
743|Ribombee|Bug · Fairy|
744|Rockruff|Rock|745
745|Lycanroc|Rock|
746|Wishiwashi|Water|
747|Mareanie|Poison · Water|748
748|Toxapex|Poison · Water|
749|Mudbray|Ground|750
750|Mudsdale|Ground|
751|Dewpider|Water · Bug|752
752|Araquanid|Water · Bug|
753|Fomantis|Grass|754
754|Lurantis|Grass|
755|Morelull|Grass · Fairy|756
756|Shiinotic|Grass · Fairy|
757|Salandit|Poison · Fire|758
758|Salazzle|Poison · Fire|
759|Stufful|Normal · Fighting|760
760|Bewear|Normal · Fighting|
761|Bounsweet|Grass|762
762|Steenee|Grass|763
763|Tsareena|Grass|
764|Comfey|Fairy|
765|Oranguru|Normal · Psychic|
766|Passimian|Fighting|
767|Wimpod|Bug · Water|768
768|Golisopod|Bug · Water|
769|Sandygast|Ghost · Ground|770
770|Palossand|Ghost · Ground|
771|Pyukumuku|Water|
772|Type: Null|Normal|773
773|Silvally|Normal|
774|Minior|Rock · Flying|
775|Komala|Normal|
776|Turtonator|Fire · Dragon|
777|Togedemaru|Electric · Steel|
778|Mimikyu|Ghost · Fairy|
779|Bruxish|Water · Psychic|
780|Drampa|Normal · Dragon|
781|Dhelmise|Ghost · Grass|
782|Jangmo-o|Dragon|783
783|Hakamo-o|Dragon · Fighting|784
784|Kommo-o|Dragon · Fighting|
785|Tapu Koko|Electric · Fairy|
786|Tapu Lele|Psychic · Fairy|
787|Tapu Bulu|Grass · Fairy|
788|Tapu Fini|Water · Fairy|
789|Cosmog|Psychic|790
790|Cosmoem|Psychic|791
791|Solgaleo|Psychic · Steel|
792|Lunala|Psychic · Ghost|
793|Nihilego|Rock · Poison|
794|Buzzwole|Bug · Fighting|
795|Pheromosa|Bug · Fighting|
796|Xurkitree|Electric|
797|Celesteela|Steel · Flying|
798|Kartana|Grass · Steel|
799|Guzzlord|Dark · Dragon|
800|Necrozma|Psychic|
801|Magearna|Steel · Fairy|
802|Marshadow|Fighting · Ghost|
803|Poipole|Poison|804
804|Naganadel|Poison · Dragon|
805|Stakataka|Rock · Steel|
806|Blacephalon|Fire · Ghost|
807|Zeraora|Electric|
808|Meltan|Steel|809
809|Melmetal|Steel|
810|Grookey|Grass|811
811|Thwackey|Grass|812
812|Rillaboom|Grass|
813|Scorbunny|Fire|814
814|Raboot|Fire|815
815|Cinderace|Fire|
816|Sobble|Water|817
817|Drizzile|Water|818
818|Inteleon|Water|
819|Skwovet|Normal|820
820|Greedent|Normal|
821|Rookidee|Flying|822
822|Corvisquire|Flying|823
823|Corviknight|Flying · Steel|
824|Blipbug|Bug|825
825|Dottler|Bug · Psychic|826
826|Orbeetle|Bug · Psychic|
827|Nickit|Dark|828
828|Thievul|Dark|
829|Gossifleur|Grass|830
830|Eldegoss|Grass|
831|Wooloo|Normal|832
832|Dubwool|Normal|
833|Chewtle|Water|834
834|Drednaw|Water · Rock|
835|Yamper|Electric|836
836|Boltund|Electric|
837|Rolycoly|Rock|838
838|Carkol|Rock · Fire|839
839|Coalossal|Rock · Fire|
840|Applin|Grass · Dragon|841
841|Flapple|Grass · Dragon|
842|Appletun|Grass · Dragon|
843|Silicobra|Ground|844
844|Sandaconda|Ground|
845|Cramorant|Flying · Water|
846|Arrokuda|Water|847
847|Barraskewda|Water|
848|Toxel|Electric · Poison|849
849|Toxtricity|Electric · Poison|
850|Sizzlipede|Fire · Bug|851
851|Centiskorch|Fire · Bug|
852|Clobbopus|Fighting|853
853|Grapploct|Fighting|
854|Sinistea|Ghost|855
855|Polteageist|Ghost|
856|Hatenna|Psychic|857
857|Hattrem|Psychic|858
858|Hatterene|Psychic · Fairy|
859|Impidimp|Dark · Fairy|860
860|Morgrem|Dark · Fairy|861
861|Grimmsnarl|Dark · Fairy|
862|Obstagoon|Dark · Normal|
863|Perrserker|Steel|
864|Cursola|Ghost|
865|Sirfetch’d|Fighting|
866|Mr. Rime|Ice · Psychic|
867|Runerigus|Ground · Ghost|
868|Milcery|Fairy|869
869|Alcremie|Fairy|
870|Falinks|Fighting|
871|Pincurchin|Electric|
872|Snom|Ice · Bug|873
873|Frosmoth|Ice · Bug|
874|Stonjourner|Rock|
875|Eiscue|Ice|
876|Indeedee|Psychic · Normal|
877|Morpeko|Electric · Dark|
878|Cufant|Steel|879
879|Copperajah|Steel|
880|Dracozolt|Electric · Dragon|
881|Arctozolt|Electric · Ice|
882|Dracovish|Water · Dragon|
883|Arctovish|Water · Ice|
884|Duraludon|Steel · Dragon|1018
885|Dreepy|Dragon · Ghost|886
886|Drakloak|Dragon · Ghost|887
887|Dragapult|Dragon · Ghost|
888|Zacian|Fairy|
889|Zamazenta|Fighting|
890|Eternatus|Poison · Dragon|
891|Kubfu|Fighting|892
892|Urshifu|Fighting · Dark|
893|Zarude|Dark · Grass|
894|Regieleki|Electric|
895|Regidrago|Dragon|
896|Glastrier|Ice|
897|Spectrier|Ghost|
898|Calyrex|Psychic · Grass|
899|Wyrdeer|Normal · Psychic|
900|Kleavor|Bug · Rock|
901|Ursaluna|Ground · Normal|
902|Basculegion|Water · Ghost|
903|Sneasler|Fighting · Poison|
904|Overqwil|Dark · Poison|
905|Enamorus|Fairy · Flying|
906|Sprigatito|Grass|907
907|Floragato|Grass|908
908|Meowscarada|Grass · Dark|
909|Fuecoco|Fire|910
910|Crocalor|Fire|911
911|Skeledirge|Fire · Ghost|
912|Quaxly|Water|913
913|Quaxwell|Water|914
914|Quaquaval|Water · Fighting|
915|Lechonk|Normal|916
916|Oinkologne|Normal|
917|Tarountula|Bug|918
918|Spidops|Bug|
919|Nymble|Bug|920
920|Lokix|Bug · Dark|
921|Pawmi|Electric|922
922|Pawmo|Electric · Fighting|923
923|Pawmot|Electric · Fighting|
924|Tandemaus|Normal|925
925|Maushold|Normal|
926|Fidough|Fairy|927
927|Dachsbun|Fairy|
928|Smoliv|Grass · Normal|929
929|Dolliv|Grass · Normal|930
930|Arboliva|Grass · Normal|
931|Squawkabilly|Normal · Flying|
932|Nacli|Rock|933
933|Naclstack|Rock|934
934|Garganacl|Rock|
935|Charcadet|Fire|936
936|Armarouge|Fire · Psychic|
937|Ceruledge|Fire · Ghost|
938|Tadbulb|Electric|939
939|Bellibolt|Electric|
940|Wattrel|Electric · Flying|941
941|Kilowattrel|Electric · Flying|
942|Maschiff|Dark|943
943|Mabosstiff|Dark|
944|Shroodle|Poison · Normal|945
945|Grafaiai|Poison · Normal|
946|Bramblin|Grass · Ghost|947
947|Brambleghast|Grass · Ghost|
948|Toedscool|Ground · Grass|949
949|Toedscruel|Ground · Grass|
950|Klawf|Rock|
951|Capsakid|Grass|952
952|Scovillain|Grass · Fire|
953|Rellor|Bug|954
954|Rabsca|Bug · Psychic|
955|Flittle|Psychic|956
956|Espathra|Psychic|
957|Tinkatink|Fairy · Steel|958
958|Tinkatuff|Fairy · Steel|959
959|Tinkaton|Fairy · Steel|
960|Wiglett|Water|961
961|Wugtrio|Water|
962|Bombirdier|Flying · Dark|
963|Finizen|Water|964
964|Palafin|Water|
965|Varoom|Steel · Poison|966
966|Revavroom|Steel · Poison|
967|Cyclizar|Dragon · Normal|
968|Orthworm|Steel|
969|Glimmet|Rock · Poison|970
970|Glimmora|Rock · Poison|
971|Greavard|Ghost|972
972|Houndstone|Ghost|
973|Flamigo|Flying · Fighting|
974|Cetoddle|Ice|975
975|Cetitan|Ice|
976|Veluza|Water · Psychic|
977|Dondozo|Water|
978|Tatsugiri|Dragon · Water|
979|Annihilape|Fighting · Ghost|
980|Clodsire|Poison · Ground|
981|Farigiraf|Normal · Psychic|
982|Dudunsparce|Normal|
983|Kingambit|Dark · Steel|
984|Great Tusk|Ground · Fighting|
985|Scream Tail|Fairy · Psychic|
986|Brute Bonnet|Grass · Dark|
987|Flutter Mane|Ghost · Fairy|
988|Slither Wing|Bug · Fighting|
989|Sandy Shocks|Electric · Ground|
990|Iron Treads|Ground · Steel|
991|Iron Bundle|Ice · Water|
992|Iron Hands|Fighting · Electric|
993|Iron Jugulis|Dark · Flying|
994|Iron Moth|Fire · Poison|
995|Iron Thorns|Rock · Electric|
996|Frigibax|Dragon · Ice|997
997|Arctibax|Dragon · Ice|998
998|Baxcalibur|Dragon · Ice|
999|Gimmighoul|Ghost|1000
1000|Gholdengo|Steel · Ghost|
1001|Wo-Chien|Dark · Grass|
1002|Chien-Pao|Dark · Ice|
1003|Ting-Lu|Dark · Ground|
1004|Chi-Yu|Dark · Fire|
1005|Roaring Moon|Dragon · Dark|
1006|Iron Valiant|Fairy · Fighting|
1007|Koraidon|Fighting · Dragon|
1008|Miraidon|Electric · Dragon|
1009|Walking Wake|Water · Dragon|
1010|Iron Leaves|Grass · Psychic|
1011|Dipplin|Grass · Dragon|1019
1012|Poltchageist|Grass · Ghost|1013
1013|Sinistcha|Grass · Ghost|
1014|Okidogi|Poison · Fighting|
1015|Munkidori|Poison · Psychic|
1016|Fezandipiti|Poison · Fairy|
1017|Ogerpon|Grass|
1018|Archaludon|Steel · Dragon|
1019|Hydrapple|Grass · Dragon|
1020|Gouging Fire|Fire · Dragon|
1021|Raging Bolt|Electric · Dragon|
1022|Iron Boulder|Rock · Psychic|
1023|Iron Crown|Steel · Psychic|
1024|Terapagos|Normal|
1025|Pecharunt|Poison · Ghost|
// Custom characters (not in the National Dex). IDs must stay >= 10000 so they
// never collide with a real dex number; SpriteCache draws these locally.
10001|Nailong|Dragon · Snack|
"""
