#!/usr/bin/env python3
"""Regenerates Sources/Croissaint/Services/DesktopPet/SpeciesCatalogData.swift
from the PokeAPI CSV dumps. Run from the repo root; needs network.

One line per species, #1-#1025: `id|Name|Types|nextID`. The pet model only
understands one evolution path, so a branching line (Eevee, Slowpoke, Wurmple)
follows its lowest-dex branch; the branches it skips are still reachable,
because every species is its own entry.
"""
import csv, io, urllib.request, pathlib

BASE = "https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/"

def load(name):
    with urllib.request.urlopen(BASE + name) as r:
        return list(csv.DictReader(io.StringIO(r.read().decode("utf-8"))))

species = load("pokemon_species.csv")
names = {r["pokemon_species_id"]: r["name"] for r in load("pokemon_species_names.csv")
         if r["local_language_id"] == "9"}
type_names = {r["id"]: r["identifier"].capitalize() for r in load("types.csv")}
types = {}
for r in sorted(load("pokemon_types.csv"), key=lambda r: int(r["slot"])):
    types.setdefault(r["pokemon_id"], []).append(type_names[r["type_id"]])

evolves_to = {}
for r in species:
    if r["evolves_from_species_id"]:
        evolves_to.setdefault(r["evolves_from_species_id"], []).append(r["id"])

lines = []
for r in sorted(species, key=lambda r: int(r["id"])):
    i = r["id"]
    nxt = evolves_to.get(i, [])
    lines.append("%s|%s|%s|%s" % (
        i,
        names[i],
        " · ".join(types.get(i, ["Unknown"])),
        min(nxt, key=int) if nxt else "",
    ))

out = pathlib.Path("Sources/Croissaint/Services/DesktopPet/SpeciesCatalogData.swift")
out.write_text(
    "// SPDX-License-Identifier: GPL-3.0-or-later\n"
    "// Copyright (C) 2026 Vorssaint\n\n"
    "// Generated by Tools/gen-species-catalog.py from the PokeAPI CSV dumps.\n"
    "// The full National Dex, one line per species: id|Name|Types|nextEvolutionID.\n"
    "// Parsed at first use rather than written as struct literals, which the\n"
    "// Swift type checker takes minutes to chew through at this size.\n\n"
    'let speciesCatalogData = """\n' + "\n".join(lines) + '\n"""\n'
)
print(len(lines), "species ->", out)
