#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 chuahchengxi
"""
Measures every Pokemon's sleeping eyelids INDIVIDUALLY and rewrites the
generated block inside gen-animation-pack.py.

For each dex id without a hand-authored entry in EYE_OVERRIDES this runs
detect_eyes(tight=True) against that species' own sprite: the lid rect is the
eye's own ink box dilated across adjacent sclera/outline ink — never the old
grown blob, which slid onto cheeks and read as a mask during naps. Species
where no credible eye pair exists get an explicit None so a pack rebuild never
re-rolls the fuzzy detector for them (byte-stable output).

Hand-measured entries (the 1-100 block and the curated drops) always win;
they are skipped here.

Usage:
  python3 Tools/measure-eyelids.py            # rewrite the generated block
Requires Pillow; sprites come from the generator's cache.
"""

import importlib.util
import os
from concurrent.futures import ThreadPoolExecutor

HERE = os.path.dirname(os.path.abspath(__file__))
GEN_PATH = os.path.join(HERE, "gen-animation-pack.py")

BEGIN = "# BEGIN measured eyelids (generated by Tools/measure-eyelids.py)"
END = "# END measured eyelids (generated by Tools/measure-eyelids.py)"


def load_generator():
    spec = importlib.util.spec_from_file_location("genpack", GEN_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def fmt(pair):
    if pair is None:
        return "None"
    (lx, ly, lw, lh), (rx, ry, rw, rh) = pair
    return f"(({lx}, {ly}, {lw}, {lh}), ({rx}, {ry}, {rw}, {rh}))"


def main():
    gen = load_generator()
    manual = set(gen.EYE_OVERRIDES.keys())
    ids = [i for i in range(gen.DEX_MIN, gen.DEX_MAX + 1) if i not in manual]
    print(f"▸ measuring {len(ids)} species individually "
          f"({len(manual)} hand-authored are skipped)…")

    def measure(id_):
        img = gen.fetch(id_)
        if img is None:
            return id_, None, "skip"
        pair = gen.detect_eyes(img, tight=True)
        return id_, pair, ("ok" if pair else "none")

    pairs, statuses = {}, {}
    with ThreadPoolExecutor(max_workers=10) as pool:
        for id_, pair, status in pool.map(measure, ids):
            pairs[id_], statuses[id_] = pair, status

    ok = [i for i, s in statuses.items() if s == "ok"]
    none = [i for i, s in statuses.items() if s == "none"]
    skipped = [i for i, s in statuses.items() if s == "skip"]
    print(f"  measured lids: {len(ok)}   no-pair pinned None: {len(none)}   "
          f"no sprite: {len(skipped)}")
    if skipped:
        print(f"  NO SPRITE: {sorted(skipped)}")

    lines = [
        BEGIN,
        "# One entry per species without a hand-authored override: its lid",
        "# rects measured off its own sprite (detect_eyes(tight=True)). A None",
        '# pins "no credible eye pair on this sprite" so pack rebuilds stay',
        "# byte-stable instead of re-rolling the heuristic detector.",
        "MEASURED_EYES = {",
    ]
    for id_ in sorted(pairs):
        lines.append(f"    {id_}: {fmt(pairs[id_])},")
    lines += ["}", "EYE_OVERRIDES.update(MEASURED_EYES)", END]

    src = open(GEN_PATH).read()
    i0 = src.index(BEGIN)
    i1 = src.index(END) + len(END)
    open(GEN_PATH, "w").write(src[:i0] + "\n".join(lines) + src[i1:])
    print(f"▸ rewrote the measured block in {GEN_PATH}")
    print("  next: python3 Tools/gen-animation-pack.py to rebuild the pack")


if __name__ == "__main__":
    main()
